onflow/fcl-js

docs/examples/introducing-fcl/Flow JavaScript SDK Showcase.md
https://www.loom.com/share/37a32f5ebea24beeb3e3b0f5f01799e6
=> DOC -- [fcl] fixes syntax highlighting in fcl showcase

docs/examples/introducing-fcl/Flow JavaScript SDK Showcase.md
Also fixes more typos of "transaction".
=> DOC -- [fcl] adds missing emulator install and usage information

packages/send/CHANGELOG.md, packages/send/src/send-execute-script.js, packages/send/src/send-get-events.js
PKG -- [send] Parse JSON-CDC payloads before putting them in response
=> PKG -- [send] Parse JSON-CDC payloads before putting them in response

packages/decode/CHANGELOG.md, packages/decode/src/decode.js, packages/decode/src/decode.test.js
PKG -- [decode] No longer parse JSON-CDC data from Uint8Array in decodeResponse
=> PKG -- [decode] No longer parse JSON-CDC data from Uint8Array in decodeResponse

packages/send/CHANGELOG.md, packages/send/src/send-get-transaction-status.js
PKG -- [send] Updates sendGetTransactionStatus to parse JSON-CDC payloads
=> PKG -- [send] Updates sendGetTransactionStatus to parse JSON-CDC payloads

packages/decode/CHANGELOG.md, packages/decode/README.md, packages/decode/src/decode.js, packages/decode/src/decode.test.js
PKG -- [decode] Updates decodeResponse to decode JSON-CDC and remove data from response ADT
=> PKG -- [decode] Updates decodeResponse to decode JSON-CDC and remove data from response ADT

packages/send/CHANGELOG.md, packages/send/src/send-get-events.js
PKG -- [send] Reduce blocks into 1d events array for GetEvents
=> PKG -- [send] Reduce blocks into 1d events array for GetEvents

packages/interaction/CHANGELOG.md, packages/interaction/README.md, packages/interaction/package.json, packages/interaction/src/interaction.js
PKG -- [interaction] Updates interaction structure
=> PKG -- [interaction] Updates interaction structure

packages/send/CHANGELOG.md, packages/send/src/send-execute-script.js, packages/send/src/send-get-account.js, packages/send/src/send-get-events.js, packages/send/src/send-get-latest-block.js, packages/send/src/send-get-transaction-status.js, packages/send/src/send-transaction.js
PKG -- [send] Updates send according to the latest interaction ADT
=> PKG -- [send] Updates send according to the latest interaction ADT

packages/interaction/CHANGELOG.md, packages/interaction/README.md, packages/interaction/src/interaction.js
PKG -- [interaction] Adds resolve field to params
=> PKG -- [interaction] Adds resolve field to params

packages/sdk/CHANGELOG.md, packages/sdk/src/build/params.js, packages/sdk/src/build/proposer.js, packages/sdk/src/resolve/resolve-params.js, packages/sdk/src/sdk.test.js
PKG -- [sdk] Accepts async resolvers as params
=> PKG -- [sdk] Accepts async resolvers as params

packages/sdk/readme.md
PKG -- [sdk] Updates readme with correct resolvers
=> PKG -- [sdk] Updates readme with correct resolvers

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-params.js
PKG -- [sdk] Params resolver parses params correctly
=> PKG -- [sdk] Params resolver parses params correctly

packages/send/CHANGELOG.md, packages/send/src/send-transaction.js
PKG -- [send] Allow authorizer proposer and payer to be the same account
=> PKG -- [send] Allow authorizer proposer and payer to be the same account

packages/sdk/CHANGELOG.md, packages/sdk/src/build/authorizations.js, packages/sdk/src/build/proposer.js, packages/sdk/src/sdk.test.js
PKG -- [sdk] Proposers accept authorization object
=> PKG -- [sdk] Proposers accept authorization object

packages/fcl/README.md
=> Call `runScript`.

examples/react-simple/src/ix/GetAccount.js, examples/react-simple/src/ix/GetEvents.js, examples/react-simple/src/ix/GetLatestBlock.js, examples/react-simple/src/ix/GetTransactionStatus.js, examples/react-simple/src/ix/Ping.js, examples/react-simple/src/ix/Script.js, examples/react-simple/src/ix/Transaction.js
EXP -- Update example project according to latest sdk
=> EXP -- Update example project according to latest sdk

packages/encode/CHANGELOG.md, packages/encode/package-lock.json, packages/encode/package.json
VSN -- [encode] 0.0.2 -> 0.0.3
=> VSN -- [encode] 0.0.2 -> 0.0.3

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json
VSN -- [send] 0.0.10 -> 0.0.11
=> VSN -- [send] 0.0.10 -> 0.0.11

packages/protobuf/CHANGELOG.md, packages/protobuf/package-lock.json, packages/protobuf/package.json
VSN -- [protobuf] 0.1.2 -> 0.1.3
=> VSN -- [protobuf] 0.1.2 -> 0.1.3

packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> VSN -- [sdk] 0.0.21 -> 0.0.22

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json
=> VSN -- [fcl] 0.0.35 -> 0.0.36

packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> VSN -- [sdk] 0.0.22 -> 0.0.23

examples/react-simple/flow.json, examples/react-simple/package-lock.json, examples/react-simple/package.json, examples/react-simple/src/ix/Transaction.js, examples/react-simple/src/ix/utils/signing-function.js
EXP -- Update according to latest SDK
=> EXP -- Update according to latest SDK

packages/interaction/CHANGELOG.md, packages/interaction/README.md, packages/interaction/src/interaction.js
PKG -- [interaction] Adds arguments to ix adt structure
=> PKG -- [interaction] Adds arguments to ix adt structure

packages/interaction/CHANGELOG.md, packages/interaction/package.json
VSN -- [interaction] 0.0.7 -> 0.0.8
=> VSN -- [interaction] 0.0.7 -> 0.0.8

packages/types/CHANGELOG.md, packages/types/src/types.js, packages/types/src/types.test.js
PKG -- [types] Changes asParam to asArgument
=> PKG -- [types] Changes asParam to asArgument

packages/types/CHANGELOG.md, packages/types/package-lock.json, packages/types/package.json
=> VSN -- [types] 0.0.1 -> 0.0.2

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-arguments.js, packages/sdk/src/sdk.js
PKG -- [sdk] Adds argument resolver
=> PKG -- [sdk] Adds argument resolver

packages/encode/CHANGELOG.md, packages/encode/src/encode.js, packages/encode/src/encode.test.js
PKG -- [encode] Adds arguments to encode
=> PKG -- [encode] Adds arguments to encode

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-signatures.js
PKG -- [sdk] Adds arguments to signature resolver
=> PKG -- [sdk] Adds arguments to signature resolver

packages/send/CHANGELOG.md, packages/send/src/send-transaction.js
PKG -- [send] Adds arguments to sendTransaction
=> PKG -- [send] Adds arguments to sendTransaction

packages/sdk/src/resolve/resolve-arguments.js
PKG -- [sdk] Corrects variable used in resolve-arguments
=> PKG -- [sdk] Corrects variable used in resolve-arguments

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json
VSN -- [send] 0.0.12 -> 0.0.13
=> VSN -- [send] 0.0.12 -> 0.0.13

packages/encode/CHANGELOG.md, packages/encode/package-lock.json, packages/encode/package.json
VSN -- [encode] 0.0.3 -> 0.0.4
=> VSN -- [encode] 0.0.3 -> 0.0.4

packages/types/CHANGELOG.md
PKG -- [types] Updates changelog to reflect published version
=> PKG -- [types] Updates changelog to reflect published version

packages/sdk/src/build/invariant.js, packages/sdk/src/sdk.js
PKG -- [sdk] Adds invariant builder
=> PKG -- [sdk] Adds invariant builder

packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/resolve/resolve-signatures.js
=> VSN -- [sdk] 0.0.23 -> 0.0.24

packages/six-create-account/package-lock.json, packages/six-create-account/package.json
PKG -- [six] Bump dependencies
=> PKG -- [six] Bump dependencies

packages/sdk/CHANGELOG.md, packages/sdk/readme.md
PKG -- [sdk] Updates to Readme according to SDK changes
=> PKG -- [sdk] Updates to Readme according to SDK changes

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/resolve/index.js
PKG -- [fcl] Updates FCL's resolve implementation
=> PKG -- [fcl] Updates FCL's resolve implementation

packages/send/CHANGELOG.md, packages/send/src/send-execute-script.js
PKG -- [send] Adds arguments for scripts
=> PKG -- [send] Adds arguments for scripts

packages/types/CHANGELOG.md, packages/types/README.md, packages/types/package-lock.json, packages/types/package.json
=> VSN -- [types] 0.0.2 -> 0.0.3

packages/protobuf/CHANGELOG.md, packages/protobuf/README.md, packages/protobuf/package-lock.json, packages/protobuf/package.json
VSN -- [protobuf] 0.1.3 -> 0.1.4
=> VSN -- [protobuf] 0.1.3 -> 0.1.4

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json
VSN -- [send] 0.0.13 -> 0.0.14
=> VSN -- [send] 0.0.13 -> 0.0.14

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json
=> VSN -- [fcl] 0.0.40 -> 0.0.41

packages/six-create-account/CHANGELOG.md, packages/six-create-account/package-lock.json, packages/six-create-account/package.json
PKG -- [six] Update SDK dependency version
=> PKG -- [six] Update SDK dependency version

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-ref-block-id.js, packages/sdk/src/sdk.js
PKG -- [sdk] Adds refBlockId resolver
=> PKG -- [sdk] Adds refBlockId resolver

packages/util-uid/CHANGELOG.md, packages/util-uid/README.md, packages/util-uid/package-lock.json, packages/util-uid/package.json, packages/util-uid/src/util-uid.js, packages/util-uid/src/util-uid.test.js
PKG -- [util-uid] Initial implementation of Unique Identifier utility
=> PKG -- [util-uid] Initial implementation of Unique Identifier utility

packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> VSN -- [sdk] 0.0.27 -> 0.0.28

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json
=> VSN -- [fcl] 0.0.42 -> 0.0.43

packages/fcl/CHANGELOG.md, packages/fcl/WARNINGS.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/current-user/index.js
=> [fcl] deprecate current user fields

packages/six-set-code/CHANGELOG.md, packages/six-set-code/README.md, packages/six-set-code/package-lock.json, packages/six-set-code/package.json, packages/six-set-code/src/six-set-code.js, packages/six-set-code/src/six-set-code.test.js
Stored Interaction - Set Account Code
=> Stored Interaction - Set Account Code

packages/send/CHANGELOG.md, packages/send/README.md, packages/send/package-lock.json, packages/send/package.json
PKG -- [send] Update protobuf version
=> PKG -- [send] Update protobuf version

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json, packages/send/src/send-get-account.js
PKG -- [send] Updates getAccount according to latest AccessAPI
=> PKG -- [send] Updates getAccount according to latest AccessAPI

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json
=> PKG -- [fcl] Updates sdk

packages/fcl/CHANGELOG.md, packages/fcl/src/resolve/index.js
PKG -- [fcl] Adds resolvers `resolveRefBlockId` and `resolveProposerSequenceNumber` to fcl resolve.
=> PKG -- [fcl] Adds resolvers `resolveRefBlockId` and `resolveProposerSequenceNumber` to fcl resolve.

packages/sdk/CHANGELOG.md, packages/sdk/readme.md
PKG -- [sdk] Updates to Readme
=> PKG -- [sdk] Updates to Readme

packages/types/CHANGELOG.md, packages/types/WARNINGS.md, packages/types/src/types.js, packages/types/src/types.test.js
PKG -- [types] Deprecates numbers as values for Fix64 or UFix64 types
=> PKG -- [types] Deprecates numbers as values for Fix64 or UFix64 types

packages/types/CHANGELOG.md, packages/types/package.json
=> VSN -- [types] 0.0.3 -> 0.0.4

packages/interaction/CHANGELOG.md, packages/interaction/package-lock.json, packages/interaction/package.json, packages/interaction/src/interaction.js, packages/interaction/src/interaction.test.js
Interaction -  Implement GetBlockByHeight and GetBlockById functionality.
=> Interaction -  Implement GetBlockByHeight and GetBlockById functionality. 

packages/interaction/CHANGELOG.md, packages/interaction/README.md, packages/interaction/WARNINGS.md, packages/interaction/package.json, packages/interaction/src/interaction.js
PKG -- [interaction] Adds `block` field to the `interaction` ADT and deprecates `latestBlock`
=> PKG -- [interaction] Adds `block` field to the `interaction` ADT and deprecates `latestBlock`

packages/send/CHANGELOG.md, packages/send/WARNINGS.md, packages/send/package-lock.json, packages/send/package.json, packages/send/src/send-get-block-by-height.js, packages/send/src/send-get-block-by-id.js, packages/send/src/send-get-latest-block.js, packages/send/src/send.js
Send - Implement GetBlockByHeight and GetBlockById functionality.
=> Send - Implement GetBlockByHeight and GetBlockById functionality. 

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json, packages/send/src/send-get-latest-block.js
PKG -- [send] `sendGetLatestBlock` sets response to `block` field of response obj
=> PKG -- [send] `sendGetLatestBlock` sets response to `block` field of response obj

packages/decode/CHANGELOG.md, packages/decode/WARNINGS.md, packages/decode/package-lock.json, packages/decode/package.json, packages/decode/src/decode.js
Decode - Implement GetBlockByHeight and GetBlockById functionality.
=> Decode - Implement GetBlockByHeight and GetBlockById functionality.

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json, packages/send/src/send-get-block-by-id.js
PKG -- [send] `sendGetBlockById` transforms block id from hex string to byte array.
=> PKG -- [send] `sendGetBlockById` transforms block id from hex string to byte array.

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/fcl.js
PKG -- [fcl] Increment sdk version and expose new builder functions.
=> PKG -- [fcl] Increment sdk version and expose new builder functions.

packages/six-create-account/CHANGELOG.md, packages/six-create-account/README.md, packages/six-create-account/package-lock.json, packages/six-create-account/package.json, packages/six-create-account/src/six-create-account.js
Update create account stored interaction.
=> Update create account stored interaction.

packages/six-transfer-tokens/CHANGELOG.md, packages/six-transfer-tokens/README.md, packages/six-transfer-tokens/package-lock.json, packages/six-transfer-tokens/package.json, packages/six-transfer-tokens/src/six-transfer-tokens.js, packages/six-transfer-tokens/src/six-transfer-tokens.test.js
PKG -- [six-transfer-tokens] Initial Implementation
=> PKG -- [six-transfer-tokens] Initial Implementation

packages/six-add-new-key/CHANGELOG.md, packages/six-add-new-key/README.md, packages/six-add-new-key/package-lock.json, packages/six-add-new-key/package.json, packages/six-add-new-key/src/six-add-new-key.js, packages/six-add-new-key/src/six-add-new-key.test.js
PKG -- [six-add-new-key] Initial Implementation
=> PKG -- [six-add-new-key] Initial Implementation

packages/six-set-code/CHANGELOG.md, packages/six-set-code/README.md, packages/six-set-code/package-lock.json, packages/six-set-code/package.json, packages/six-set-code/src/six-set-code.js
PKG -- [six-set-code] Brings six up to date
=> PKG -- [six-set-code] Brings six up to date

packages/six-transfer-tokens/CHANGELOG.md, packages/six-transfer-tokens/package-lock.json, packages/six-transfer-tokens/package.json
VSN -- [six-transfer-tokens] 0.0.0 -> 0.0.1
=> VSN -- [six-transfer-tokens] 0.0.0 -> 0.0.1

packages/six-create-account/CHANGELOG.md, packages/six-create-account/package-lock.json, packages/six-create-account/package.json
VSN -- [six-create-account] 0.0.0 -> 0.0.1
=> VSN -- [six-create-account] 0.0.0 -> 0.0.1

packages/six-add-new-key/CHANGELOG.md, packages/six-add-new-key/package-lock.json, packages/six-add-new-key/package.json
VSN -- [six-add-new-key] 0.0.0 -> 0.0.1
=> VSN -- [six-add-new-key] 0.0.0 -> 0.0.1

packages/six-set-code/CHANGELOG.md, packages/six-set-code/package-lock.json, packages/six-set-code/package.json
VSN -- [six-set-code] 0.0.0 -> 0.0.1
=> VSN -- [six-set-code] 0.0.0 -> 0.0.1

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/current-user/render-authn-frame.js, packages/fcl/src/current-user/render-authz-frame.js
PKG -- [fcl] Authn and Authz iframes allow usb feature policy
=> PKG -- [fcl] Authn and Authz iframes allow usb feature policy

packages/six-add-new-key/package-lock.json, packages/six-add-new-key/package.json, packages/six-add-new-key/src/six-add-new-key.js
PKG -- [six-add-new-key] Fixes issue where payer was not defined.
=> PKG -- [six-add-new-key] Fixes issue where payer was not defined.

packages/protobuf/CHANGELOG.md, packages/protobuf/README.md, packages/protobuf/package.json, packages/protobuf/src/generated/flow/access/access_pb.d.ts, packages/protobuf/src/generated/flow/access/access_pb.js, packages/protobuf/src/proto/flow/access/access.proto
=> Updated protobuf definitions for BlockEvents

packages/six-transfer-tokens/CHANGELOG.md, packages/six-transfer-tokens/package-lock.json, packages/six-transfer-tokens/package.json, packages/six-transfer-tokens/src/six-transfer-tokens.js
PKG -- [six-transfer-tokens] Adds multi-network support for transfer tokens stored interaction
=> PKG -- [six-transfer-tokens] Adds multi-network support for transfer tokens stored interaction

packages/encode/package-lock.json, packages/encode/package.json, packages/encode/src/encode.js, packages/encode/src/rlp-flow.js
- remove the rlp dependency completely.
- removed the package from encode
- removed the BN dependency on the rlp code
- moved the encode code to use the new rlp-flow.
=> PKG -- [encode] removing rlp dependency from encode, removed BN from rlp code

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/current-user/render-frame.js, packages/fcl/src/fcl.js
PKG -- [fcl] Allows iframe feature policy to allow usb on all contexts
=> PKG -- [fcl] Allows iframe feature policy to allow usb on all contexts

packages/six-withdraw-unlocked-flow/CHANGELOG.md, packages/six-withdraw-unlocked-flow/README.md, packages/six-withdraw-unlocked-flow/package-lock.json, packages/six-withdraw-unlocked-flow/package.json, packages/six-withdraw-unlocked-flow/src/six-withdraw-unlocked-flow.js, packages/six-withdraw-unlocked-flow/src/six-withdraw-unlocked-flow.test.js
PKG -- [six-withdraw-unlocked-flow] Initial implementation
=> PKG -- [six-withdraw-unlocked-flow] Initial implementation

packages/six-deposit-unlocked-flow/CHANGELOG.md, packages/six-deposit-unlocked-flow/README.md, packages/six-deposit-unlocked-flow/package-lock.json, packages/six-deposit-unlocked-flow/package.json, packages/six-deposit-unlocked-flow/src/six-deposit-unlocked-flow.js, packages/six-deposit-unlocked-flow/src/six-deposit-unlocked-flow.test.js
PKG -- [six-deposit-unlocked-flow] Initial implementation
=> PKG -- [six-deposit-unlocked-flow] Initial implementation

packages/six-register-node/CHANGELOG.md, packages/six-register-node/README.md, packages/six-register-node/package-lock.json, packages/six-register-node/package.json, packages/six-register-node/src/six-register-node.js, packages/six-register-node/src/six-register-node.test.js
PKG -- [six-register-node] Initial implementation
=> PKG -- [six-register-node] Initial implementation

packages/six-register-node/src/six-register-node.js, packages/six-stake-new-locked-flow/CHANGELOG.md, packages/six-stake-new-locked-flow/README.md, packages/six-stake-new-locked-flow/package-lock.json, packages/six-stake-new-locked-flow/package.json, packages/six-stake-new-locked-flow/src/six-stake-new-locked-flow.js, packages/six-stake-new-locked-flow/src/six-stake-new-locked-flow.test.js
PKG -- [six-stake-new-locked-flow] Initial Implementation
=> PKG -- [six-stake-new-locked-flow] Initial Implementation

packages/six-restake-unstaked-flow/CHANGELOG.md, packages/six-restake-unstaked-flow/README.md, packages/six-restake-unstaked-flow/package-lock.json, packages/six-restake-unstaked-flow/package.json, packages/six-restake-unstaked-flow/src/six-restake-unstaked-flow.js, packages/six-restake-unstaked-flow/src/six-restake-unstaked-flow.test.js
PKG -- [six-restake-unstaked-flow] Initial implementation
=> PKG -- [six-restake-unstaked-flow] Initial implementation

packages/six-restake-rewarded-flow/CHANGELOG.md, packages/six-restake-rewarded-flow/README.md, packages/six-restake-rewarded-flow/package-lock.json, packages/six-restake-rewarded-flow/package.json, packages/six-restake-rewarded-flow/src/six-restake-rewarded-flow.js, packages/six-restake-rewarded-flow/src/six-restake-rewarded-flow.test.js
PKG -- [six-restake-rewarded-flow] Initial Implementation
=> PKG -- [six-restake-rewarded-flow] Initial Implementation

packages/six-unstake-flow/CHANGELOG.md, packages/six-unstake-flow/README.md, packages/six-unstake-flow/package-lock.json, packages/six-unstake-flow/package.json, packages/six-unstake-flow/src/six-unstake-flow.js, packages/six-unstake-flow/src/six-unstake-flow.test.js
PKG -- [six-unstake-flow] Initial implementation
=> PKG -- [six-unstake-flow] Initial implementation

packages/six-register-node/src/six-register-node.js, packages/six-restake-rewarded-flow/src/six-restake-rewarded-flow.js, packages/six-restake-unstaked-flow/src/six-restake-unstaked-flow.js, packages/six-stake-new-locked-flow/src/six-stake-new-locked-flow.js, packages/six-withdraw-unstaked-flow/CHANGELOG.md, packages/six-withdraw-unstaked-flow/README.md, packages/six-withdraw-unstaked-flow/package-lock.json, packages/six-withdraw-unstaked-flow/package.json, packages/six-withdraw-unstaked-flow/src/six-withdraw-unstaked-flow.js, packages/six-withdraw-unstaked-flow/src/six-withdraw-unstaked-flow.test.js
PKG -- [six-withdraw-unstaked-flow] Initial implementation
=> PKG -- [six-withdraw-unstaked-flow] Initial implementation

packages/six-withdraw-rewarded-flow/CHANGELOG.md, packages/six-withdraw-rewarded-flow/README.md, packages/six-withdraw-rewarded-flow/package-lock.json, packages/six-withdraw-rewarded-flow/package.json, packages/six-withdraw-rewarded-flow/src/six-withdraw-rewarded-flow.js, packages/six-withdraw-rewarded-flow/src/six-withdraw-rewarded-flow.test.js
PKG -- [six-withdraw-rewarded-flow] Initial implementation
=> PKG -- [six-withdraw-rewarded-flow] Initial implementation

packages/six-register-delegator/CHANGELOG.md, packages/six-register-delegator/README.md, packages/six-register-delegator/package-lock.json, packages/six-register-delegator/package.json, packages/six-register-delegator/src/six-register-delegator.js, packages/six-register-delegator/src/six-register-delegator.test.js
PKG -- [six-register-delegator] Initial implementation
=> PKG -- [six-register-delegator] Initial implementation

packages/six-delegate-new-locked-flow/CHANGELOG.md, packages/six-delegate-new-locked-flow/README.md, packages/six-delegate-new-locked-flow/package-lock.json, packages/six-delegate-new-locked-flow/package.json, packages/six-delegate-new-locked-flow/src/six-delegate-new-locked-flow.js, packages/six-delegate-new-locked-flow/src/six-delegate-new-locked-flow.test.js
PKG -- [six-delegate-new-locked-flow] Initial Implementation
=> PKG -- [six-delegate-new-locked-flow] Initial Implementation

packages/six-redelegate-unstaked-flow/CHANGELOG.md, packages/six-redelegate-unstaked-flow/README.md, packages/six-redelegate-unstaked-flow/package-lock.json, packages/six-redelegate-unstaked-flow/package.json, packages/six-redelegate-unstaked-flow/src/six-redelegate-unstaked-flow.js, packages/six-redelegate-unstaked-flow/src/six-redelegate-unstaked-flow.test.js
PKG -- [six-redelegate-unstaked-flow] Initial implementation
=> PKG -- [six-redelegate-unstaked-flow] Initial implementation

packages/six-redelegate-rewarded-flow/CHANGELOG.md, packages/six-redelegate-rewarded-flow/README.md, packages/six-redelegate-rewarded-flow/package-lock.json, packages/six-redelegate-rewarded-flow/package.json, packages/six-redelegate-rewarded-flow/src/six-redelegate-rewarded-flow.js, packages/six-redelegate-rewarded-flow/src/six-redelegate-rewarded-flow.test.js
PKG -- [six-redelegate-rewarded-flow] Initial Implementation
=> PKG -- [six-redelegate-rewarded-flow] Initial Implementation

packages/six-unstake-delegated-flow/CHANGELOG.md, packages/six-unstake-delegated-flow/README.md, packages/six-unstake-delegated-flow/package-lock.json, packages/six-unstake-delegated-flow/package.json, packages/six-unstake-delegated-flow/src/six-unstake-delegated-flow.js, packages/six-unstake-delegated-flow/src/six-unstake-delegated-flow.test.js
PKG -- [six-unstake-delegated-flow] Initial implementation
=> PKG -- [six-unstake-delegated-flow] Initial implementation

packages/six-withdraw-unstaked-delegated-flow/CHANGELOG.md, packages/six-withdraw-unstaked-delegated-flow/README.md, packages/six-withdraw-unstaked-delegated-flow/package-lock.json, packages/six-withdraw-unstaked-delegated-flow/package.json, packages/six-withdraw-unstaked-delegated-flow/src/six-withdraw-unstaked-delegated-flow.js, packages/six-withdraw-unstaked-delegated-flow/src/six-withdraw-unstaked-delegated-flow.test.js
PKG -- [six-withdraw-unstaked-delegated-flow] Initial implementation
=> PKG -- [six-withdraw-unstaked-delegated-flow] Initial implementation

packages/six-get-delegator-id/CHANGELOG.md, packages/six-get-delegator-id/README.md, packages/six-get-delegator-id/package-lock.json, packages/six-get-delegator-id/package.json, packages/six-get-delegator-id/src/six-get-delegator-id.js, packages/six-get-delegator-id/src/six-get-delegator-id.test.js
PKG -- [six-get-delegator-id] Initial implemenatation
=> PKG -- [six-get-delegator-id] Initial implemenatation

packages/six-deposit-unlocked-flow/src/six-deposit-unlocked-flow.js, packages/six-register-node/src/six-register-node.js, packages/six-restake-unstaked-flow/src/six-restake-unstaked-flow.js, packages/six-stake-new-locked-flow/src/six-stake-new-locked-flow.js, packages/six-unstake-flow/src/six-unstake-flow.js, packages/six-withdraw-rewarded-flow/src/six-withdraw-rewarded-flow.js, packages/six-withdraw-unlocked-flow/src/six-withdraw-unlocked-flow.js, packages/six-withdraw-unstaked-flow/src/six-withdraw-unstaked-flow.js
PKG -- [stored-interactions] Updates six mainnet hashes where needed
=> PKG -- [stored-interactions] Updates six mainnet hashes where needed

packages/six-withdraw-rewarded-delegated-flow/CHANGELOG.md, packages/six-withdraw-rewarded-delegated-flow/README.md, packages/six-withdraw-rewarded-delegated-flow/package-lock.json, packages/six-withdraw-rewarded-delegated-flow/package.json, packages/six-withdraw-rewarded-delegated-flow/src/six-withdraw-rewarded-delegated-flow.js, packages/six-withdraw-rewarded-delegated-flow/src/six-withdraw-rewarded-delegated-flow.test.js
PKG -- [six-withdraw-rewarded-delegated-flow] Initial implementation
=> PKG -- [six-withdraw-rewarded-delegated-flow] Initial implementation

packages/six-deposit-unlocked-flow/CHANGELOG.md, packages/six-deposit-unlocked-flow/package-lock.json, packages/six-deposit-unlocked-flow/package.json, packages/six-register-node/CHANGELOG.md, packages/six-register-node/package-lock.json, packages/six-register-node/package.json, packages/six-restake-unstaked-flow/CHANGELOG.md, packages/six-restake-unstaked-flow/package-lock.json, packages/six-restake-unstaked-flow/package.json, packages/six-stake-new-locked-flow/CHANGELOG.md, packages/six-stake-new-locked-flow/package-lock.json, packages/six-stake-new-locked-flow/package.json, packages/six-unstake-flow/CHANGELOG.md, packages/six-unstake-flow/package-lock.json, packages/six-unstake-flow/package.json, packages/six-withdraw-rewarded-flow/CHANGELOG.md, packages/six-withdraw-rewarded-flow/package-lock.json, packages/six-withdraw-rewarded-flow/package.json, packages/six-withdraw-unlocked-flow/CHANGELOG.md, packages/six-withdraw-unlocked-flow/package-lock.json, packages/six-withdraw-unlocked-flow/package.json, packages/six-withdraw-unstaked-flow/CHANGELOG.md, packages/six-withdraw-unstaked-flow/package-lock.json, packages/six-withdraw-unstaked-flow/package.json
PKG -- [stored-interactions] Version bump to 0.0.2 for mainnet hash updates
=> PKG -- [stored-interactions] Version bump to 0.0.2 for mainnet hash updates

packages/six-register-node/CHANGELOG.md, packages/six-register-node/package-lock.json, packages/six-register-node/package.json, packages/six-register-node/src/six-register-node.js
VSN -- [six-register-node] 0.0.2 -> 0.0.3
=> VSN -- [six-register-node] 0.0.2 -> 0.0.3

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/current-user/exec-authz-service.js, packages/fcl/src/current-user/index.js, packages/fcl/src/current-user/validate-composite-signature.js, packages/fcl/src/fcl.js
PKG -- [fcl] sansPrefix required addresses
=> PKG -- [fcl] sansPrefix required addresses

packages/six-register-delegator/CHANGELOG.md, packages/six-register-delegator/package-lock.json, packages/six-register-delegator/package.json, packages/six-register-delegator/src/six-register-delegator.js
PKG -- [six-register-delegator] Updates transaction code
=> PKG -- [six-register-delegator] Updates transaction code

packages/six-withdraw-rewarded-flow/CHANGELOG.md, packages/six-withdraw-rewarded-flow/package-lock.json, packages/six-withdraw-rewarded-flow/package.json, packages/six-withdraw-rewarded-flow/src/six-withdraw-rewarded-flow.js
[six-withdraw-rewarded-flow] -- VSN 0.0.5
=> [six-withdraw-rewarded-flow] -- VSN 0.0.5

packages/six-register-delegator/CHANGELOG.md, packages/six-register-delegator/package-lock.json, packages/six-register-delegator/package.json, packages/six-register-delegator/src/six-register-delegator.js
[six-register-delegator] -- VSN 0.0.6
=> [six-register-delegator] -- VSN 0.0.6

packages/six-register-node/CHANGELOG.md, packages/six-register-node/package-lock.json, packages/six-register-node/package.json, packages/six-register-node/src/six-register-node.js
[six-register-node] -- VSN 0.0.6
=> [six-register-node] -- VSN 0.0.6

packages/six-unstake-all-flow/CHANGELOG.md, packages/six-unstake-all-flow/README.md, packages/six-unstake-all-flow/package-lock.json, packages/six-unstake-all-flow/package.json, packages/six-unstake-all-flow/src/six-unstake-all-flow.js, packages/six-unstake-all-flow/src/six-unstake-all-flow.test.js
[six-unstake-all-flow] -- VSN 0.0.1
=> [six-unstake-all-flow] -- VSN 0.0.1

packages/six-withdraw-rewarded-delegated-flow/CHANGELOG.md, packages/six-withdraw-rewarded-delegated-flow/package-lock.json, packages/six-withdraw-rewarded-delegated-flow/package.json, packages/six-withdraw-rewarded-delegated-flow/src/six-withdraw-rewarded-delegated-flow.js, packages/six-withdraw-rewarded-flow/CHANGELOG.md, packages/six-withdraw-rewarded-flow/package-lock.json, packages/six-withdraw-rewarded-flow/package.json, packages/six-withdraw-rewarded-flow/src/six-withdraw-rewarded-flow.js
Six - updates reward transactions
[NO MERGE until ledger is updated with these transactions.]
=> [NO-MERGE] Six - updates reward transactions

packages/interaction/CHANGELOG.md, packages/interaction/README.md, packages/interaction/package-lock.json, packages/interaction/package.json, packages/interaction/src/interaction.js
=> [interaction] -- VSN 0.0.11

packages/sdk-build-get-latest-block/CHANGELOG.md, packages/sdk-build-get-latest-block/package-lock.json, packages/sdk-build-get-latest-block/package.json, packages/sdk-build-get-latest-block/src/index.js
[build-get-latest-block] -- VSN 0.0.1
=> [build-get-latest-block] -- VSN 0.0.1

packages/send/CHANGELOG.md, packages/send/package-lock.json, packages/send/package.json, packages/send/src/send-execute-script.js, packages/send/src/send-get-account.js, packages/send/src/send-get-block-header.js, packages/send/src/send-get-block.js, packages/send/src/send-get-events.js, packages/send/src/send-get-transaction-status.js
=> [send] -- VSN 0.0.36

packages/sdk-build-get-events-at-block-height-range/CHANGELOG.md, packages/sdk-build-get-events-at-block-height-range/package-lock.json, packages/sdk-build-get-events-at-block-height-range/package.json, packages/sdk-build-get-events-at-block-height-range/src/index.js, packages/sdk-build-get-events-at-block-height-range/src/index.test.js, packages/sdk-build-get-events-at-block-ids/CHANGELOG.md, packages/sdk-build-get-events-at-block-ids/package-lock.json, packages/sdk-build-get-events-at-block-ids/package.json, packages/sdk-build-get-events-at-block-ids/src/index.js, packages/sdk-build-get-events-at-block-ids/src/index.test.js, packages/sdk-build-get-events/CHANGELOG.md, packages/sdk-build-get-events/package-lock.json, packages/sdk-build-get-events/package.json, packages/sdk-build-get-events/src/index.js
=> Build get events

packages/sdk-build-get-block-header/CHANGELOG.md, packages/sdk-build-get-block-header/package-lock.json, packages/sdk-build-get-block-header/package.json, packages/sdk-build-get-block-header/src/index.js, packages/sdk-build-get-block-header/src/index.test.js
[build-get-block-header] -- VSN 0.0.0 Initial Implementation
=> [build-get-block-header] -- VSN 0.0.0 Initial Implementation

packages/sdk-build-at-block-height/CHANGELOG.md, packages/sdk-build-at-block-height/package-lock.json, packages/sdk-build-at-block-height/package.json, packages/sdk-build-at-block-height/src/index.js, packages/sdk-build-at-block-height/src/index.test.js, packages/sdk-build-at-block-id/CHANGELOG.md, packages/sdk-build-at-block-id/package-lock.json, packages/sdk-build-at-block-id/package.json, packages/sdk-build-at-block-id/src/index.js, packages/sdk-build-at-block-id/src/index.test.js, packages/sdk-build-get-block-by-height/CHANGELOG.md, packages/sdk-build-get-block-by-height/package-lock.json, packages/sdk-build-get-block-by-height/package.json, packages/sdk-build-get-block-by-height/src/index.js, packages/sdk-build-get-block-by-id/CHANGELOG.md, packages/sdk-build-get-block-by-id/package-lock.json, packages/sdk-build-get-block-by-id/package.json, packages/sdk-build-get-block-by-id/src/index.js, packages/sdk-build-get-block/CHANGELOG.md, packages/sdk-build-get-block/package-lock.json, packages/sdk-build-get-block/package.json, packages/sdk-build-get-block/src/index.js, packages/sdk-build-get-block/src/index.test.js
=> SDK Build Get Block

packages/sdk-build-get-account/CHANGELOG.md, packages/sdk-build-get-account/package-lock.json, packages/sdk-build-get-account/package.json, packages/sdk-build-get-account/src/index.js
[build-get-account] -- VSN 0.0.2
=> [build-get-account] -- VSN 0.0.2

packages/decode/CHANGELOG.md, packages/decode/package-lock.json, packages/decode/package.json, packages/decode/src/decode.js
=> [decode] -- VSN 0.0.11

packages/interaction/src/__snapshots__/interaction.test.js.snap, packages/interaction/src/interaction.js, packages/interaction/src/interaction.test.js
[interaction] -- Updated IX structure to fix JSON parse difficulties
=> [interaction] -- Updated IX structure to fix JSON parse difficulties

packages/send/package-lock.json, packages/send/package.json
[send] -- VSN interaction 0.0.11
=> [send] -- VSN interaction 0.0.11

packages/sdk-build-get-account/src/index.test.js
[sdk-build-get-account] -- Update test
=> [sdk-build-get-account] -- Update test

packages/sdk-resolve-signatures/src/__snapshots__/index.test.js.snap, packages/sdk-resolve-signatures/src/index.test.js
[sdk-resolve-signatures] -- Update test snapshots
=> [sdk-resolve-signatures] -- Update test snapshots

packages/sdk-resolve/package-lock.json
=> [resolve] -- VSN updates deps

packages/sdk-send/package-lock.json, packages/sdk-send/package.json
=> [sdk-send] -- VSN 0.0.11

packages/sdk-decode/package-lock.json, packages/sdk-decode/package.json
=> [sdk-decode] -- VSN 0.0.3

packages/sdk-account/package-lock.json, packages/sdk-account/package.json
=> [sdk-account] -- VSN 0.0.9

packages/sdk-latest-block/CHANGELOG.md, packages/sdk-latest-block/package-lock.json, packages/sdk-latest-block/package.json, packages/sdk-latest-block/src/index.js
[latest-block] -- VSN 0.0.9
Updates dependencies before merging!
=> [latest-block] -- VSN 0.0.9

packages/fcl/src/fcl.js
=> [fcl] -- Adds version number

packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/contract.test.js, packages/sdk/src/decode/sdk-decode.js, packages/sdk/src/sdk.js
=> [sdk] -- VSN 0.0.45-alpha.5

packages/fcl/package-lock.json, packages/fcl/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/resolve/resolve.js
=> [fcl] -- VSN 0.0.68-alpha.4

packages/fcl/src/fcl.js
=> Fcl/vsn 0.0.68 alpha.4

packages/fcl/package-lock.json, packages/fcl/package.json, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/resolve/resolve.js, packages/sdk/src/send/send.js
=> [fcl] -- VSN 0.0.68-alpha.5

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/send/send-execute-script.js, packages/sdk/src/send/send-get-account.js
[fcl] -- VSN 0.0.68-alpha.9
Addresses: https://github.com/onflow/flow-js-sdk/issues/542
=> [fcl] -- VSN 0.0.68-alpha.9

packages/fcl/src/fcl.js
=> Fcl/vsn 0.0.68 alpha.9

README.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/fcl.js, packages/sdk/TRANSITIONS.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/build/build-get-events-at-block-ids.js
=> [sdk] -- VSN 0.0.45-alpha.11

packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/fcl.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/decode/decode.js, packages/sdk/src/decode/decode.test.js, packages/sdk/src/interaction/interaction.js, packages/sdk/src/send/send-get-events.js
=> [sdk] -- VSN 0.0.45-alpha.12

packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/fcl.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/send/sdk-send.js
=> [sdk] -- VSN 0.0.45-alpha.15

packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/fcl.js, packages/sdk/package.json, packages/sdk/src/send/send-get-account.js
=> [sdk] -- VSN 0.0.45-alpha.17

packages/sdk/CHANGELOG.md, packages/sdk/src/build/build-metadata.js, packages/sdk/src/build/build-metadata.test.js, packages/sdk/src/interaction/interaction.js
Add metadata obj and makeMeta function to update ix
=> PKG -- [interaction] Add metadata to ix

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-accounts.js, packages/sdk/src/resolve/resolve-accounts.test.js, packages/sdk/src/sdk.js
- Added metadata field to preSignable in resolve-accounts
- export meta from sdk.js
=> [sdk] Add metadata to preSignable

packages/sdk/CHANGELOG.md, packages/sdk/src/build/build-limit.js
- Removed unnecessary pipe() from build-limit.js
=> [sdk] Internal Update build-limit

packages/sdk/CHANGELOG.md, packages/sdk/src/build/build-metadata.js, packages/sdk/src/build/build-metadata.test.js, packages/sdk/src/resolve/__snapshots__/resolve-signatures.test.js.snap, packages/sdk/src/resolve/resolve-accounts.test.js, packages/sdk/src/resolve/resolve-signatures.test.js
- Added validation to build-meta.js
- Added tests for validation error
=> [sdk] Add metadata validation

packages/sdk/CHANGELOG.md
- Added `meta` details and code example to CHANGLEOG
=> [sdk] Update CHANGELOG with metadata details for release

packages/sdk/CHANGELOG.md, packages/sdk/src/build/build-authorizations.js, packages/sdk/src/build/build-authorizations.test.js, packages/sdk/src/build/build-payer.js, packages/sdk/src/build/build-proposer.js, packages/sdk/src/interaction/interaction.js
- Added `makeAccountRole` to interaction for use in build-authorizations, build-payer, build-proposer
=> [sdk] Update interaction, add prepAccount

packages/sdk/CHANGELOG.md, packages/sdk/src/sdk.js, packages/sdk/src/send/send-get-account.js, packages/sdk/src/send/send-get-account.test.js
[sdk] -- Fixes accessing TextDecoder in an node environment
=> [sdk] -- Fixes accessing TextDecoder in an node environment

README.md
Just noticed a broken link, and fixed it.
=> [docs] Fix link in README

packages/sdk/src/build/build-at-block-height.js
- Initial removal from atBlockHeight and interaction recPipe
=> [sdk]  Remove OK/BAD for deprecation

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> [sdk] -- VSN 0.0.45-alpha.19

packages/sdk/CHANGELOG.md, packages/sdk/src/encode/README.md, packages/sdk/src/encode/encode.js, packages/sdk/src/encode/encode.test.js, packages/sdk/src/resolve/resolve-signatures.js
- Update naming of `script` and `gasLimit` to `cadence` and `computeLimit`
=> [sdk] Update encoding naming to match voucher and message

packages/sdk/CHANGELOG.md, packages/sdk/src/interaction/interaction.js, packages/sdk/src/utils/deprecate.js, packages/sdk/src/utils/index.js
- Moved interaction type checks to /utils for reuse
=> [sdk] -- Move type check utils

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> [fcl] -- VSN 0.0.68

six/six-set-code/src/six-set-code.js
[six] -- Fixes issue in building package
=> [six] -- Fixes issue in building package

packages/sdk/CHANGELOG.md, packages/sdk/src/response/README.md, packages/sdk/src/response/__snapshots__/response.test.js.snap, packages/sdk/src/response/response.js, packages/sdk/src/response/response.test.js
[sdk] -- Updates shape of response ADT
=> [sdk] -- Updates shape of response ADT

packages/sdk/CHANGELOG.md, packages/sdk/src/send/send-get-block.js
[sdk] -- Decodes signatures in block responses from byte arrays to hex strings
=> [sdk] -- Decodes signatures in block responses from byte arrays to hex strings

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> [sdk] -- VSN 0.0.46-alpha.1

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> [fcl] -- VSN 0.0.70

six/fusd/six-fusd-setup/CHANGELOG.md, six/fusd/six-fusd-setup/README.md, six/fusd/six-fusd-setup/package-lock.json, six/fusd/six-fusd-setup/package.json, six/fusd/six-fusd-setup/src/six-fusd-setup.js, six/fusd/six-fusd-setup/src/six-fusd-setup.test.js, six/fusd/six-fusd-transfer/CHANGELOG.md, six/fusd/six-fusd-transfer/README.md, six/fusd/six-fusd-transfer/package-lock.json, six/fusd/six-fusd-transfer/package.json, six/fusd/six-fusd-transfer/src/six-fusd-transfer.js, six/fusd/six-fusd-transfer/src/six-fusd-transfer.test.js
[six] -- Adds stored interactions for FUSD
=> [six] -- Adds stored interactions for FUSD

six/fusd/six-fusd-transfer/CHANGELOG.md, six/fusd/six-fusd-transfer/README.md, six/fusd/six-fusd-transfer/package-lock.json, six/fusd/six-fusd-transfer/package.json, six/fusd/six-fusd-transfer/src/six-fusd-transfer.js
[six] -- Update six-fusd-transfer with correct template arguments
=> [six] -- Update six-fusd-transfer with correct template arguments

six/fusd/six-fusd-transfer/CHANGELOG.md, six/fusd/six-fusd-transfer/package-lock.json, six/fusd/six-fusd-transfer/package.json, six/fusd/six-fusd-transfer/src/six-fusd-transfer.js
[six] -- six-fusd-transfer update
=> [six] -- six-fusd-transfer update

six/fusd/six-fusd-setup/CHANGELOG.md, six/fusd/six-fusd-setup/src/six-fusd-setup.js, six/fusd/six-fusd-transfer/src/six-fusd-transfer.js
[six] -- Makes fusd stored interactions async
=> [six] -- Makes fusd stored interactions async

six/six-add-new-key/package-lock.json, six/six-add-new-key/package.json
[six] -- VSN six-add-new-key 0.0.6 -> 0.0.7
=> [six] -- VSN six-add-new-key 0.0.6 -> 0.0.7

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-frame.js
=> [fcl] -- VSN 0.0.71-alpha.1

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> [fcl] -- VSN 0.0.71

packages/fcl/src/wallet-provider-spec/user-signature.md
- Add user-signature documentation to wallet-provider spec
=> [fcl] Add user-signature documentation for wallet-providers

docs/index.mdx
per https://github.com/onflow/flow/issues/495
=> Remove mentions of `@onflow/sdk` from intro.

packages/sdk/CHANGELOG.md, packages/sdk/src/sdk.js, packages/sdk/src/wallet-utils/encode-signable.js, packages/sdk/src/wallet-utils/encode-signable.test.js, packages/sdk/src/wallet-utils/index.js
[sdk] -- Adds encode message from signable wallet utility
=> [sdk] -- Adds encode message from signable wallet utility

packages/sdk/readme.md
Updates links in SDK package #666
=> [docs] fixes #666

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/fcl/src/fcl.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json
=> [fcl] -- VSN 0.0.72

six/staking-collection/six-stakingcollection-setup-staking-collection/CHANGELOG.md, six/staking-collection/six-stakingcollection-setup-staking-collection/package-lock.json, six/staking-collection/six-stakingcollection-setup-staking-collection/package.json, six/staking-collection/six-stakingcollection-setup-staking-collection/src/six-stakingcollection-setup-staking-collection.js, six/staking-collection/six-stakingcollection-transfer-delegator/CHANGELOG.md, six/staking-collection/six-stakingcollection-transfer-delegator/package-lock.json, six/staking-collection/six-stakingcollection-transfer-delegator/package.json, six/staking-collection/six-stakingcollection-transfer-delegator/src/six-stakingcollection-transfer-delegator.js, six/staking-collection/six-stakingcollection-transfer-node/CHANGELOG.md, six/staking-collection/six-stakingcollection-transfer-node/package.json, six/staking-collection/six-stakingcollection-transfer-node/src/six-stakingcollection-transfer-node.js, six/staking-collection/six-stakingcollection-unstake-all/CHANGELOG.md, six/staking-collection/six-stakingcollection-unstake-all/package-lock.json, six/staking-collection/six-stakingcollection-unstake-all/package.json, six/staking-collection/six-stakingcollection-unstake-all/src/six-stakingcollection-unstake-all.js
[six] -- Updates Staking Collection stored interactions.
=> [six] -- Updates Staking Collection stored interactions.

six/staking-collection/six-stakingcollection-transfer-node/CHANGELOG.md, six/staking-collection/six-stakingcollection-transfer-node/package-lock.json, six/staking-collection/six-stakingcollection-transfer-node/package.json, six/staking-collection/six-stakingcollection-transfer-node/src/six-stakingcollection-transfer-node.js
[six] -- Updates transfer node staking collection stored interaction
=> [six] -- Updates transfer node staking collection stored interaction

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/__snapshots__/resolve-signatures.test.js.snap, packages/sdk/src/resolve/resolve-accounts.test.js, packages/sdk/src/resolve/resolve-signatures.js, packages/sdk/src/resolve/resolve-signatures.test.js
- Added `payer` signature to `payloadSigs` on `voucher` to resolve [#684](https://github.com/onflow/flow-js-sdk/issues/684)
- Update resolve-account, resolve-signature tests, snapshot
=> [sdk] -- Update voucher to include payer signature

six/staking-collection/six-stakingcollection-setup-staking-collection/CHANGELOG.md, six/staking-collection/six-stakingcollection-setup-staking-collection/package-lock.json, six/staking-collection/six-stakingcollection-setup-staking-collection/package.json, six/staking-collection/six-stakingcollection-setup-staking-collection/src/six-stakingcollection-setup-staking-collection.js
[six] -- Updates Staking Collection Setup Staking Collection Stored Interaction
=> [six] -- Updates Staking Collection Setup Staking Collection Stored Interaction

six/staking-collection/six-stakingcollection-request-unstaking/CHANGELOG.md, six/staking-collection/six-stakingcollection-request-unstaking/package-lock.json, six/staking-collection/six-stakingcollection-request-unstaking/package.json, six/staking-collection/six-stakingcollection-request-unstaking/src/six-stakingcollection-request-unstaking.js, six/staking-collection/six-stakingcollection-stake-new-tokens/CHANGELOG.md, six/staking-collection/six-stakingcollection-stake-new-tokens/package-lock.json, six/staking-collection/six-stakingcollection-stake-new-tokens/package.json, six/staking-collection/six-stakingcollection-stake-new-tokens/src/six-stakingcollection-stake-new-tokens.js, six/staking-collection/six-stakingcollection-stake-rewarded-tokens/CHANGELOG.md, six/staking-collection/six-stakingcollection-stake-rewarded-tokens/package-lock.json, six/staking-collection/six-stakingcollection-stake-rewarded-tokens/package.json, six/staking-collection/six-stakingcollection-stake-rewarded-tokens/src/six-stakingcollection-stake-rewarded-tokens.js, six/staking-collection/six-stakingcollection-stake-unstaked-tokens/CHANGELOG.md, six/staking-collection/six-stakingcollection-stake-unstaked-tokens/package-lock.json, six/staking-collection/six-stakingcollection-stake-unstaked-tokens/package.json, six/staking-collection/six-stakingcollection-stake-unstaked-tokens/src/six-stakingcollection-stake-unstaked-tokens.js, six/staking-collection/six-stakingcollection-withdraw-rewarded-tokens/CHANGELOG.md, six/staking-collection/six-stakingcollection-withdraw-rewarded-tokens/package-lock.json, six/staking-collection/six-stakingcollection-withdraw-rewarded-tokens/package.json, six/staking-collection/six-stakingcollection-withdraw-rewarded-tokens/src/six-stakingcollection-withdraw-rewarded-tokens.js, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/CHANGELOG.md, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/package-lock.json, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/package.json, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/src/six-stakingcollection-withdraw-unstaked-tokens.js
[six] -- Repairs argument syntax in some Staking Collection stored interactions.
=> [six] -- Repairs argument syntax in some Staking Collection stored interactions.

six/staking-collection/six-stakingcollection-register-delegator/CHANGELOG.md, six/staking-collection/six-stakingcollection-register-delegator/package-lock.json, six/staking-collection/six-stakingcollection-register-delegator/package.json, six/staking-collection/six-stakingcollection-register-delegator/src/six-stakingcollection-register-delegator.js
[six] -- Updates register delegator staking collection stored interaction
=> [six] -- Updates register delegator staking collection stored interaction

packages/fcl/src/fcl.test.js
Updates serialize test to stay aligned with latest `sdk.createSignableVoucher` from sdk dependency
=> [fcl] -- Update serialize test

six/staking-collection/six-stakingcollection-transfer-delegator/CHANGELOG.md, six/staking-collection/six-stakingcollection-transfer-delegator/package-lock.json, six/staking-collection/six-stakingcollection-transfer-delegator/package.json, six/staking-collection/six-stakingcollection-transfer-delegator/src/six-stakingcollection-transfer-delegator.js
[six] -- Updates Staking Collection Transfer Delegator Stored Interaction
=> [six] -- Updates Staking Collection Transfer Delegator Stored Interaction

six/staking-collection/six-stakingcollection-create-machine-account/CHANGELOG.md, six/staking-collection/six-stakingcollection-create-machine-account/README.md, six/staking-collection/six-stakingcollection-create-machine-account/package-lock.json, six/staking-collection/six-stakingcollection-create-machine-account/package.json, six/staking-collection/six-stakingcollection-create-machine-account/src/six-stakingcollection-create-machine-account.js, six/staking-collection/six-stakingcollection-create-machine-account/src/six-stakingcollection-create-machine-account.test.js
[six] -- Adds Stored Interaction for creating a machine account for a node in a staking collection
=> [six] -- Adds Stored Interaction for creating a machine account for a node in a staking collection

packages/fcl/CHANGELOG.md, packages/fcl/src/serialize/index.js
Fixes resolveFinalNormalization bug
=> [fcl] Update setting serialize resolveFunction

six/staking-collection/six-stakingcollection-register-node/README.md, six/staking-collection/six-stakingcollection-register-node/package-lock.json, six/staking-collection/six-stakingcollection-register-node/package.json, six/staking-collection/six-stakingcollection-register-node/src/six-stakingcollection-register-node.js
[six] -- Adds support for submitting optional public keys along with staking collection node registration
=> [six] -- Adds support for submitting optional public keys along with staking collection node registration

docs/user-signature.mdx
- Adds expected return values/types
=> [root] -- Update user-signature doc

packages/sdk/CHANGELOG.md, packages/sdk/src/decode/decode.js, packages/sdk/src/decode/decode.test.js
[sdk] -- Adds support for decoding `Type` and `Path` JSON-CDC payloads.
=> [sdk] -- Adds support for decoding `Type` and `Path` JSON-CDC payloads.

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/VERSION.js
=> [fcl] -- VSN 0.0.75

packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/VERSION.js, packages/sdk/src/send/send-get-account.js
=> [fcl] -- VSN 0.0.76

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/index.js, packages/fcl/src/current-user/exec-service/strategies/pop-rpc.js, packages/fcl/src/current-user/exec-service/strategies/utils/frame.js, packages/fcl/src/current-user/exec-service/strategies/utils/pop.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-frame.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-pop.js, packages/fcl/src/current-user/index.js, packages/fcl/src/fcl.js, packages/fcl/src/wallet-utils/index.js, packages/fcl/src/wallet-utils/send-msg-to-fcl.js
- Add `WalletUtils.sendMsgToFCL` and defaults to `POP/RPC` for `IFRAME/RPC` strategy
=> [fcl] EXPERIMENTAL Pop-up replacement for iFrame

packages/types/CHANGELOG.md, packages/types/package-lock.json, packages/types/package.json, packages/types/src/types.js, packages/types/src/types.test.js
[types] -- Declaring a `UFix64` value without prodviding a correctly formatted fractional throws an error.
=> [types] -- Declaring a `UFix64` value without prodviding a correctly formatted fractional throws an error.

packages/sdk/CHANGELOG.md, packages/sdk/src/decode/decode.js, packages/sdk/src/decode/decode.test.js
[sdk] -- Adds support for decoding `Enum` and `Capability` JSON-CDC payloads.
=> [sdk] -- Adds support for decoding `Enum` and `Capability` JSON-CDC payloads.

packages/fcl/CHANGELOG.md, packages/fcl/package.json, packages/fcl/src/VERSION.js, packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/VERSION.js
=> [fcl] -- VSN 0.0.77-alpha.1

docs/api.md
Some formatting changes were necessary to make this page appear properly on the docs site.
=> [docs] -- API page formatting improvements

README.md
* updated outdated links in README
=> Update README outdated links

LICENSE
Filling in the missing copyright information in the LICENSE
=> Inserting copyright in license

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
=> [fcl] -- VSN 0.0.77-alpha.2

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/exec-local.js, packages/fcl/src/current-user/exec-service/index.js, packages/fcl/src/current-user/exec-service/strategies/tab-rpc.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-frame.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-tab.js, packages/fcl/src/current-user/exec-service/strategies/utils/tab.js
- Adds `execTabRPC`, `renderTab`, `tab`
=> [fcl] Add TAB/RPC and VIEW/TAB

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
=> [fcl] -- VSN 0.0.77-alpha.3

six/staking-collection/six-stakingcollection-update-networking-address/CHANGELOG.md, six/staking-collection/six-stakingcollection-update-networking-address/README.md, six/staking-collection/six-stakingcollection-update-networking-address/package-lock.json, six/staking-collection/six-stakingcollection-update-networking-address/package.json, six/staking-collection/six-stakingcollection-update-networking-address/src/six-stakingcollection-update-networking-address.js, six/staking-collection/six-stakingcollection-update-networking-address/src/six-stakingcollection-update-networking-address.test.js
[six] -- Adds stored interaction six-stakingcollection-update-networking-address
=> [six] -- Adds stored interaction six-stakingcollection-update-networking-address

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-accounts.js, packages/sdk/src/resolve/resolve-signatures.js, packages/sdk/src/resolve/voucher.js, packages/sdk/src/sdk.js
- Update `createSignableVoucher` structure and move to separate module
=> [sdk] Update voucher structure and extract createSignableVoucher

six/staking-collection/six-stakingcollection-setup-staking-collection/CHANGELOG.md, six/staking-collection/six-stakingcollection-setup-staking-collection/package-lock.json, six/staking-collection/six-stakingcollection-setup-staking-collection/package.json, six/staking-collection/six-stakingcollection-setup-staking-collection/src/six-stakingcollection-setup-staking-collection.js
[six] -- VSN six-stakingcollection-setup-staking-collection 0.0.5 -> 0.0.6
=> [six] -- VSN six-stakingcollection-setup-staking-collection 0.0.5 -> 0.0.6

six/staking-collection/six-stakingcollection-transfer-node/CHANGELOG.md, six/staking-collection/six-stakingcollection-transfer-node/package-lock.json, six/staking-collection/six-stakingcollection-transfer-node/package.json, six/staking-collection/six-stakingcollection-transfer-node/src/six-stakingcollection-transfer-node.js
[six] -- VSN six-stakingcollection-transfer-node 0.0.5 -> 0.0.6
=> [six] -- VSN six-stakingcollection-transfer-node 0.0.5 -> 0.0.6

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/strategies/iframe-rpc.js, packages/fcl/src/wallet-utils/on-message-from-fcl.js
=> [fcl] Update frame onReady response

six/staking-collection/six-stakingcollection-transfer-delegator/CHANGELOG.md, six/staking-collection/six-stakingcollection-transfer-delegator/package-lock.json, six/staking-collection/six-stakingcollection-transfer-delegator/package.json, six/staking-collection/six-stakingcollection-transfer-delegator/src/six-stakingcollection-transfer-delegator.js, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/CHANGELOG.md, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/package-lock.json, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/package.json, six/staking-collection/six-stakingcollection-withdraw-unstaked-tokens/src/six-stakingcollection-withdraw-unstaked-tokens.js
https://github.com/onflow/flow-js-sdk/pull/new/six/stakingcollection-withdraw-unstaked-tokens-0.0.5
=> [six] -- VSN six-stakingcollection-withdraw-unstaked-tokens 0.0.5

packages/fcl/CHANGELOG.md, packages/fcl/src/wallet-utils/index.js, packages/fcl/src/wallet-utils/send-msg-to-fcl.js
=> [fcl] Add additional wallet utils

packages/fcl/src/wallet-provider-spec/draft-v3.md
[DOC] -- Adds 3rd draft of the FCL wallet provider spec docs
=> [DOC] -- Adds 3rd draft of the FCL wallet provider spec docs

CODEOWNERS
Add @gregsantos and myself as code owners to repo.
=> PKG -- [root] update code owners

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
VSN -- [fcl] 0.0.77-alpha.4 -> 0.0.77-alpha.5
=> VSN -- [fcl] 0.0.77-alpha.4 -> 0.0.77

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/strategies/pop-rpc.js, packages/fcl/src/current-user/exec-service/strategies/tab-rpc.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-pop.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-tab.js, packages/fcl/src/current-user/index.js
- If not logged-in, redirects rather opening new a window
=> [fcl] Adds redirect for pop/tab when unauthenticated

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
VSN -- [fcl] 0.0.77-> 0.0.78-alpha.1
=> VSN -- [fcl] 0.0.77-> 0.0.78-alpha.1

docs/proving-authentication.mdx, packages/fcl/src/wallet-provider-spec/provable-authn.md
DOC -- [fcl] Adds initial FCL Proving User Authentication docs
=> DOC -- [fcl] Adds initial FCL Proving User Authentication docs

docs/reference/proving-authentication.mdx
DOC -- [fcl] Updates FCL Provable authn docs
=> DOC -- [fcl] Updates FCL Provable authn docs

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
[fcl] -- VSN 0.0.78-alpha.1 -> 0.0.78-alpha.2
=> [fcl] -- VSN 0.0.78-alpha.1 -> 0.0.78-alpha.2

six/topshot/six-topshot-setup-collection/CHANGELOG.md, six/topshot/six-topshot-setup-collection/README.md, six/topshot/six-topshot-setup-collection/package-lock.json, six/topshot/six-topshot-setup-collection/package.json, six/topshot/six-topshot-setup-collection/src/six-topshot-setup-collection.js, six/topshot/six-topshot-setup-collection/src/six-topshot-setup-collection.test.js, six/topshot/six-topshot-transfer-moment/CHANGELOG.md, six/topshot/six-topshot-transfer-moment/README.md, six/topshot/six-topshot-transfer-moment/package-lock.json, six/topshot/six-topshot-transfer-moment/package.json, six/topshot/six-topshot-transfer-moment/src/six-topshot-transfer-moment.js, six/topshot/six-topshot-transfer-moment/src/six-topshot-transfer-moment.test.js
Adds initial NBA Top Shot stored interactions
=> Adds initial NBA Top Shot stored interactions

six/topshot/six-topshot-setup-collection/package-lock.json, six/topshot/six-topshot-transfer-moment/package-lock.json
[six] -- [six-topshot-transfer-moment] Updates NBA Top Shot stored interactions
=> [six] -- [six-topshot-transfer-moment] Updates NBA Top Shot stored interactions

packages/sdk/CHANGELOG.md
Fix changelog to match formatting of FCL package.
=> PKG -- [sdk] Fix changelog formatting

packages/sdk/src/interaction/interaction.js
Default method should exist for JSON parse of arg.
=> PKG -- [sdk] Add resolveArgument default

packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/VERSION.js
=> VSN -- [sdk] 0.0.54 -> 0.0.55

docs/tutorials/flow-app-quickstart.md
Made some minor edits throughout the doc:
- Added extra callouts for files
- Changed the order of the top section to config first then change app.js
- added links to docs URLs (as relative paths don't work on docs site)
- More small ones...
=> DOC -- [root] FCL Quickstart Edits

docs/reference/proving-authentication.mdx, packages/fcl/CHANGELOG.md, packages/fcl/src/config-utils.js, packages/fcl/src/default-config.js, packages/fcl/src/wallet-provider-spec/provable-authn.md
- Removes default since it's an optional config value
- Updates docs to consistently use `appDomainTag`
=> [fcl] remove default appDomainTag

six/fusd/six-fusd-setup/CHANGELOG.md, six/fusd/six-fusd-setup/package-lock.json, six/fusd/six-fusd-setup/package.json, six/fusd/six-fusd-setup/src/six-fusd-setup.js, six/fusd/six-fusd-transfer/CHANGELOG.md, six/fusd/six-fusd-transfer/package-lock.json, six/fusd/six-fusd-transfer/package.json, six/fusd/six-fusd-transfer/src/six-fusd-transfer.js
SIX - fusd transaction code updates
=> SIX - fusd transaction code updates

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/strategies/utils/pop.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-pop.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-tab.js, packages/fcl/src/current-user/exec-service/strategies/utils/tab.js
=> [fcl] update pop/tab to reject on close

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
VSN -- [fcl] 0.0.78-alpha.6 -> 0.0.78-alpha.7
=> [fcl] 0.0.78-alpha.6 -> 0.0.78-alpha.7

packages/types/CHANGELOG.md, packages/types/README.md, packages/types/package-lock.json, packages/types/package.json, packages/types/src/types.js, packages/types/src/types.test.js
PKG -- [types] Adds Path type
```javascript
import * as t from "@onflow/types"
sdk.build([
sdk.args([
sdk.arg(
{
domain: "public"                // public | private | storage
identifier: "flowTokenVault"
}
t.Path
)
])
])
```
=> PKG -- [types] Adds Path type

packages/types/README.md
DOC -- [types] Moves Path to correct location in document
=> DOC -- [types] Moves Path to correct location in document

packages/fcl/CHANGELOG.md, packages/fcl/src/exec/verify.js
=> [fcl] Add CHANGELOG for community contribution

packages/sdk/src/resolve/resolve-cadence.js, packages/sdk/src/resolve/resolve-cadence.test.js
Address Issue: https://github.com/onflow/fcl-js/issues/884
=> PKG -- [sdk] Replace all cadence addresses

packages/sdk/src/resolve/resolve-cadence.js, packages/sdk/src/resolve/resolve-cadence.test.js
Addresses Issue: https://github.com/onflow/fcl-js/issues/887
=> PKG -- [sdk] Fix similar address replacement issue

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/config-utils.js, packages/fcl/src/discovery/services.js, packages/fcl/src/discovery/services.test.js
Addresses: https://github.com/onflow/fcl-js/issues/899
=> PKG -- [fcl] Add service opt-in functionality to config

packages/fcl/CHANGELOG.md, packages/fcl/package-lock.json, packages/fcl/package.json, packages/fcl/src/VERSION.js
VSN -- [fcl] 0.0.78-alpha.8 -> 0.0.78-alpha.9
=> VSN -- [fcl] 0.0.78-alpha.8 -> 0.0.78-alpha.9

README.md
in the documentation, package can be installed with yarn and npm but only npm is described. 
so, i added shell commend for yarn
=> update Readme.md with install package with yarn

docs/reference/api.md, docs/reference/proving-authentication.mdx, docs/reference/user-signatures.mdx, packages/fcl/CHANGELOG.md, packages/fcl/src/exec/verify.js
=> DOC -- [fcl] Correct all refs to verifyUserSignature

packages/sdk/CHANGELOG.md, packages/sdk/src/interaction/interaction.js
Addresses: https://github.com/onflow/fcl-js/issues/890
=> PKG -- [sdk] Fix context error for resolveArgument

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
Addresses: https://github.com/onflow/fcl-js/issues/931
=> PKG -- [fcl] fix currentUser as arg error

packages/fcl/src/wallet-provider-spec/draft-v3.md
- wallet-provider-spec/draft-v3
=> [fcl] Add Authentication Refresh spec

docs/reference/proving-authentication.mdx
- Clarify Domain Separation Tag wording
- Add note on MITM
=> DOC -- [fcl] Update pauthn doc

packages/fcl/README.md
=> DOC -- [fcl] Fix README typo

packages/fcl/CHANGELOG.md
Addresses: https://github.com/onflow/fcl-js/issues/959
=> PKG -- [fcl] Add changelog for app service redirect config

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
Addresses: https://github.com/onflow/fcl-js/issues/962
=> PKG -- [fcl] Respect discovery wallet method for API

docs/reference/api.md
- Add clearer explanation of Discovery
- Change naming of state vars to make it easier to understand
=> DOC -- [root] Discovery docs improvements

packages/sdk/CHANGELOG.md, packages/sdk/src/block/block.js
Addresses: https://github.com/onflow/fcl-js/issues/987
=> PKG -- [sdk] SDK circular dependency fix

packages/transport-http/CHANGELOG.md, packages/transport-http/package-lock.json, packages/transport-http/package.json, packages/transport-http/src/send-transaction.js, packages/transport-http/src/send-transaction.test.js
PKG -- [transport-http] Removes signer_index from Envelope and Payload signatures
=> PKG -- [transport-http] Removes signer_index from Envelope and Payload signatures

packages/transport-grpc/CHANGELOG.md, packages/transport-grpc/package-lock.json, packages/transport-grpc/package.json, packages/transport-grpc/src/send-get-transaction-status.js, packages/transport-grpc/src/send-get-transaction-status.test.js, packages/transport-http/CHANGELOG.md, packages/transport-http/package-lock.json, packages/transport-http/package.json, packages/transport-http/src/send-get-transaction-status.js, packages/transport-http/src/send-get-transaction-status.test.js
VSN -- [transport-grpc] 0.0.1 -> 0.0.2
=> VSN -- [transport-grpc] 0.0.1 -> 0.0.2

packages/transport-grpc/package-lock.json
PKG -- [transport-grpc] Adds package-lock
=> PKG -- [transport-grpc] Adds package-lock

README.md, docs/index.md, docs/index.mdx
found some broken link on the last merge - need another stamp for quick fix.
=> fix broken links on readme

packages/fcl/CHANGELOG.md, packages/fcl/src/fcl.js
=> [fcl] expose voucherIntercept from sdk

packages/transport-http/CHANGELOG.md, packages/transport-http/package-lock.json, packages/transport-http/package.json, packages/transport-http/src/send-get-transaction-status.js, packages/transport-http/src/send-get-transaction-status.test.js
PKG -- [transport-http] VSN 0.0.4 -> 0.0.5
=> PKG -- [transport-http] VSN 0.0.4 -> 0.0.5

packages/transport-http/CHANGELOG.md, packages/transport-http/package-lock.json, packages/transport-http/package.json, packages/transport-http/src/send-get-account.js
VSN -- [transport-http] 0.0.5 -> 0.0.6
=> VSN -- [transport-http] 0.0.5 -> 0.0.6

six/six-add-new-key/CHANGELOG.md, six/six-add-new-key/README.md, six/six-add-new-key/package-lock.json, six/six-add-new-key/package.json, six/six-add-new-key/src/six-add-new-key.js, six/six-create-account/CHANGELOG.md, six/six-create-account/README.md, six/six-create-account/package-lock.json, six/six-create-account/package.json, six/six-create-account/src/six-create-account.js
Create Account / Add Key Stored Interaction Updates
=> Create Account / Add Key Stored Interaction Updates

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
Addresses: https://github.com/onflow/fcl-js/issues/1026
=> PKG -- [fcl] Remove redirect warning

README.md, package-lock.json, package.json
Added top level `build` command
Added how to build in readme
=> Add build readme

six/usdc/six-usdc-setup/package-lock.json, six/usdc/six-usdc-setup/package.json, six/usdc/six-usdc-setup/src/six-usdc-setup.js, six/usdc/six-usdc-transfer/package.json
PKG -- [six-usdc-transfer] Update package.json with package name
=> PKG -- [six-usdc-transfer] Update package.json with package name

docs/reference/scripts.mdx, docs/reference/transactions.mdx
Addresses: https://github.com/onflow/fcl-js/issues/1085
=> Update scripts and transactions examples

packages/fcl/CHANGELOG.md, packages/fcl/src/events/index.js
PKG -- [fcl] Use latest SDK methods in fcl events subscriber
=> PKG -- [fcl] Use latest SDK methods in fcl events subscriber

packages/fcl/.npmignore
Addresses: https://github.com/onflow/fcl-js/issues/1121
=> PKG -- [fcl] Remove assets from build

packages/sdk/src/response/README.md, packages/transport-grpc/CHANGELOG.md, packages/transport-grpc/src/send-get-block.js, packages/transport-grpc/src/send-get-block.test.js, packages/transport-http/CHANGELOG.md, packages/transport-http/src/send-get-block.js, packages/transport-http/src/send-get-block.test.js
Addresses: https://github.com/onflow/fcl-js/issues/1116
=> PKG -- [transport] Remove block signatures

.changeset/blue-pianos-search.md, packages/sdk/src/response/README.md, packages/transport-grpc/src/send-get-transaction-status.js, packages/transport-grpc/src/send-get-transaction-status.test.js, packages/transport-http/src/send-get-transaction-status.js, packages/transport-http/src/send-get-transaction-status.test.js
PKG -- [transport] Add blockId to GetTransactionStatus response
=> PKG -- [transport] Add blockId to GetTransactionStatus response

.changeset/late-hounds-judge.md, packages/transport-http/src/http-request.js
PKG -- [transport-http] Expose error returned from AN through HTTPRequestError
=> PKG -- [transport-http] Expose error returned from AN through HTTPRequestError

packages/fcl/src/current-user/exec-service/index.js
=> PKG -- [fcl] Add extensions to config.client

.changeset/fair-files-reply.md, packages/transport-http/src/http-request.js
PKG -- [transport-http] Propagate HTTP error in node environments
=> PKG -- [transport-http] Propagate HTTP error in node environments

.changeset/dull-poems-think.md, packages/fcl/src/current-user/index.js, packages/util-actor/src/index.js
=> [util-actor] Update util-actor root registry

docs/reference/api.md
=> [root] add AppUtils, verifyAccountProof api

docs/reference/api.md, docs/reference/sdk-guidelines.mdx, docs/tutorials/flow-app-quickstart.mdx
[DOC] -- Update accessNode.api examples to point to rest api
=> [DOC] -- Update accessNode.api examples to point to rest api

docs/tutorials/flow-app-quickstart.mdx
Fixed a typo and reduced embed size
=> Typo and better video embed size

docs/tutorials/flow-app-quickstart.mdx
src is auto generated by create-react-app, this project uses create-next-app and the flow folder was created earlier in the tutorial.
=> Change src/config to flow/config

docs/tutorials/flow-app-quickstart.mdx
Link to Discovery docs on Quickstart.
=> DOC -- [root] Add discovery link to quickstart

.changeset/tidy-keys-heal.md, packages/transport-http/src/http-request.js
I have defaulted to 1000ms delay and 5 attempts but this is configurable in the parameters of httpRequest.  This functionality could be added to the opts for all of the transport-http functions and passed on to httpRequest.
Prettier butchered the file which is why so many lines are changed.
=> PKG -- [transport-http] Retry timed out requests

docs/tutorials/flow-app-quickstart.mdx
Fixes the config code snippet where the profile contract is introduced to be updated to FCL 1.0
=> DOC -- [root] Fix config for FCL 1.0

.changeset/empty-ants-switch.md, docs/reference/api.md, packages/fcl/src/events/index.js
@JeffreyDoyle 
[#995](https://github.com/onflow/fcl-js/issues/955)
=> PKG -- [fcl]  fix block height issue in events subcriber

CODEOWNERS
OPS -- Add srinjoyc as CODEOWNER
=> OPS -- Add srinjoyc as CODEOWNER

README.md
DOC -- Add FCL release notes callout to FCL project README
=> DOC -- Add FCL release notes callout to FCL project README

README.md, docs/index.md, docs/index.mdx
- Updates api ref
- Updates README
=> [root] Adds Lilico to current wallet providers

docs/reference/transactions.mdx
Minor typo correction in FCL docs.
=> DOC -- [fcl] fix transactions.mdx typo

.changeset/poor-cheetahs-sin.md, package-lock.json, packages/transport-http/package.json, packages/transport-http/src/http-request.js
Will deprecate/remove util-node-http-modules in another PR
=> PKG -- [transport-http] Replace util-node-http-modules with node-fetch

docs/reference/api.md, docs/reference/sdk-guidelines.mdx
Cleanup getTransaction, getTransactionStatus, TransactionObject, TransactionStatusObject, ProposalKey in api.md
=> PKG -- [docs] Cleanup transaction docs in api.md

.changeset/perfect-houses-join.md, .changeset/wet-brooms-tap.md, package-lock.json, packages/sdk/src/resolve/resolve-accounts.js, packages/sdk/src/resolve/resolve-accounts.test.js, packages/sdk/src/test-utils/authz-fn.js, packages/transport-http/src/send-transaction.js
=> PKG -- [sdk] Fix erroneous sansPrefix requirement for acct.addr in authorization function

.changeset/brown-bears-remain.md, packages/fcl/src/discovery/utils.js
Addresses: https://github.com/onflow/fcl-js/issues/1374
=> PKG -- [fcl] Respect service method for discovery

docs/flow-docs.json
this content is also defined in the onflow/developer-portal repo
https://github.com/onflow/developer-portal/blob/e0b9e225c252cb7ef8d8325a519e6f21f503d626/app/constants/doc-collections.server.ts#L1004
adding this file will allow sidebar entries to be managed in this repo,
instead
https://github.com/onflow/developer-portal/issues/616
=> Setup a docs configuration file used by developers.flow.com

docs/flow-docs.json
DOC -- Adds interaction template to docs sidebar
=> DOC -- Adds interaction template to docs sidebar

docs/reference/interaction-templates.mdx
DOC -- Query Interaction Template by POST search request
=> DOC -- Query Interaction Template by POST search request

docs/reference/interaction-templates.mdx
DOC -- Updates Interaction Template doc with auditor addresses
=> DOC -- Updates Interaction Template doc with auditor addresses

.changeset/rich-countries-taste.md, packages/fcl/src/exec/utils/prep-template-opts.js
PKG -- [fcl] Hotfix to FCL query mutate prep ops
=> PKG -- [fcl] Hotfix to FCL query mutate prep ops

.changeset/tricky-buses-decide.md, packages/fcl/src/exec/utils/prep-template-opts.js
PKG -- [fcl] Fix circular dep in FCL prep-template-opts
=> PKG -- [fcl] Fix circular dep in FCL prep-template-opts

.changeset/pretty-crabs-repair.md, packages/fcl/src/interaction-template-utils/generate-template-interface-id.js
PKG -- [fcl] Hotfix to generate template interface id util
=> PKG -- [fcl] Hotfix to generate template interface id util

.changeset/short-llamas-kiss.md, packages/fcl/src/interaction-template-utils/get-interaction-template-audits.js
PKG -- [fcl] Adds mainnet Interaction Template Audit contract to Interaction Template Utils
=> PKG -- [fcl] Adds mainnet Interaction Template Audit contract to Interaction Template Utils

docs/reference/interaction-templates.mdx
DOC -- Adds Flow Team Auditor MainNet address
=> DOC -- Adds Flow Team Auditor MainNet address

docs/flow-docs.json
=> [root] add ref to flow-docs for sidebar

docs/reference/wallet-connect.mdx
=> [root] close br 2

.changeset/perfect-pumpkins-visit.md, package-lock.json, packages/config/package.json, packages/rlp/package.json, packages/transport-grpc/package.json, packages/types/package.json, packages/util-actor/package.json, packages/util-address/package.json, packages/util-encode-key/package.json, packages/util-invariant/package.json, packages/util-logger/package.json, packages/util-template/package.json, packages/util-uid/package.json
Changeset only updates dependencies for packages that have are releasing as part of the current release plan. Cleaning up references to alpha package.
=> [OPS] - Upgrade @onflow/fcl-bundle 1.2.0-alpha.0 -> 1.2.0

.changeset/two-islands-rush.md, packages/config/src/config.js
=> PKG -- [config] Fix config overload prone to race condition

docs/reference/api.md, docs/reference/discovery.mdx, docs/reference/scripts.mdx, docs/reference/sdk-guidelines.mdx, docs/reference/user-signatures.mdx
=> [root] update verify user signatures reference

.changeset/brown-eggs-sparkle.md, packages/types/src/types.js, packages/types/src/types.test.js
PKG -- [types] Adds Enum support
Closes: https://github.com/onflow/fcl-js/issues/1465
=> PKG -- [types] Adds Enum support

.changeset/pretty-deers-heal.md, packages/transport-grpc/src/unary.js
PKG -- [transport-grpc] Retry on 503/504 status errors
=> PKG -- [transport-grpc] Retry on 503/504 status errors

.changeset/two-cars-worry.md, packages/transport-grpc/src/unary.js
This reverts commit d1ad4c02a62e09548554bbf75df2ce3b8bd3fca5.
=> Revert "PKG -- [transport-grpc] Retry on 503/504 status errors"

packages/config/src/config.js
Tentative. I might be understanding how to do JSdoc horribly wrong.
=> Add types to config

.changeset/seven-rules-travel.md, packages/util-address/src/index.js
=> PKG --  [util-address] Add JSDoc to util address

.changeset/swift-birds-fold.md, packages/util-uid/src/util-uid.js
=> PKG -- [util-uid] Add JSDoc for uid package

packages/util-invariant/src/index.js
=> PKG -- [util-invariant] Add JSDoc for invariant package

docs/reference/api.md
See https://developers.flow.com/cadence/language/values-and-types#fixed-point-numbers
=> Fix documentation for account balance format

docs/reference/api.md
There are a few links getting failed by link checker. Fixing to verify link checker is working correctly
=> Update api.md to fix dead links identified by link checker

packages/util-logger/src/util-logger.js
=> PKG -- [util-logger] Add JSDoc

packages/util-encode-key/src/index.js
=> PKG -- [util-encode-key] Add JSDoc

docs/index.md, docs/reference/discovery.mdx
closes: https://github.com/onflow/fcl-js/issues/1529
fix link to docs.meetdapper.com
=> Fix links to docs.meetdapper.com

packages/fcl/src/utils/getChainId.js
=> PKG -- [fcl] Add JSDoc for chain id file

packages/util-template/src/template.js
=> PKG -- [template] Add jsdoc

packages/config/src/config.js
=> PKG -- [config] Add jsdoc to config method

packages/fcl/src/events/index.js
=> PKG -- [fcl] JSDoc for events

packages/fcl/src/discovery/services/authn.js
=> PKG -- [fcl] Add discovery jsdoc

packages/config/src/config.js
=> PKG -- [config] Add optionals

packages/sdk/package.json
Addresses: https://github.com/onflow/fcl-js/issues/1536
=> PKG -- [sdk] Add packages for lint

docs/reference/api.md
=> DOC - Fix incorrect description

.changeset/nasty-toes-kneel.md, packages/sdk/package.json
updated transport-http dependency
=> VSN -- [sdk] updated transport-http dependency

.changeset/witty-scissors-boil.md, packages/config/src/config.js, packages/fcl/src/fcl.js
Addresses: https://github.com/onflow/fcl-js/issues/1603
Also let's dev import types from fcl instead of package
=> PKG -- [config] Fix types

docs/reference/api.md
=> update to fix missing end line

.changeset/metal-steaks-bake.md, packages/config/utils/utils.js, packages/config/utils/utils.test.js
Addresses: https://github.com/onflow/fcl-js/issues/1625
=> PKG -- [config] Fix key warning

package-lock.json, packages/util-actor/package.json
Fixes https://github.com/onflow/fcl-js/issues/1617
=> PKG [fcl-actor] -- Upgrade queue-microtask to latest

.changeset/orange-years-clap.md, package-lock.json, packages/util-actor/package.json
[PKG -- [util-actor] Upgrade queue-microtask to latest
=> PKG -- [util-actor] Upgrade queue-microtask to latest

.changeset/smooth-wasps-impress.md, packages/fcl/src/transaction/index.js, packages/typedefs/src/index.js
Addresses: https://github.com/onflow/fcl-js/issues/1635
=> PKG -- [fcl/typedefs] Add types to fcl.tx

packages/sdk/src/resolve/resolve-accounts.js
=> PKG -- [sdk] fixed infinite loop

README.md
Addresses: https://github.com/onflow/fcl-js/issues/1674
=> PKG -- [root] Add TypeScript info to readme

.changeset/unlucky-beans-visit.md, packages/fcl/src/fcl.js
Addresses: https://github.com/onflow/fcl-js/issues/1683
=> PKG -- [fcl] Add types to t object in query/mutate args fn

.changeset/funny-waves-search.md, packages/fcl/src/current-user/exec-service/strategies/http-post.js, packages/fcl/src/utils/react-native/exec-local.js, packages/fcl/src/utils/react-native/render-browser.js
=> PKG -- [fcl] Stop polling when React Native WebBrowser closed

.changeset/big-mangos-explode.md, packages/sdk/src/resolve/__tests__/resolve-accounts.test.js, packages/sdk/src/resolve/resolve-accounts.test.js, packages/sdk/src/test-utils/authz-fn.js
removed tempId from testing accounts
=> PKG -- [sdk] fixed tests

.changeset/wild-days-kiss.md, packages/sdk/src/build/build-arguments.js, packages/sdk/src/build/build-at-block-height.js, packages/sdk/src/build/build-get-account.js, packages/sdk/src/build/build-get-block-header.js, packages/sdk/src/build/build-get-block.js, packages/sdk/src/build/build-get-collection.js, packages/sdk/src/build/build-get-events-at-block-height-range.js, packages/sdk/src/build/build-get-events-at-block-ids.js, packages/sdk/src/build/build-get-transaction-status.js, packages/sdk/src/build/build-get-transaction.js, packages/sdk/src/build/build-transaction.js, packages/sdk/src/send/send.js
=> PKG -- [sdk] Fixed return types

README.md
release and prerelease instruction
=> DOC -- [root] release and prerelease instruction

.changeset/six-cherries-clap.md, packages/fcl/src/current-user/index.js, packages/fcl/src/discovery/services.js, packages/fcl/src/discovery/utils.js
Addresses: https://github.com/onflow/fcl-js/issues/1774
=> PKG -- [FCL] Send suggested features to Discovery

.changeset/cyan-feet-heal.md, packages/transport-http/src/http-request.js, packages/transport-http/src/http-request.test.js
=> PKG -- [transport-http] Use URL to join httpRequest hostname to path

.changeset/hungry-trains-agree.md, packages/fcl-core/src/exec/query.js
closes: #https://github.com/onflow/fcl-js/issues/1836
make query template type same as transaction template type
=> make query template type same as transaction template type

packages/config/src/config.test.ts, packages/config/src/utils/utils.test.ts, packages/config/src/utils/utils.ts
=> feat: add support for new `dependencies` field in flow.json

package-lock.json
The project Using `onflow/fcl-js` has used babel to compile code that was specifically crafted by an attacker can lead to arbitrary code execution during compilation, when using plugins that rely on the path.evaluate()or path.evaluateTruthy() internal Babel methods.
Affected by this project `discord-interactions-js` is vulnerable to Incomplete List of Unallowed Inputs when using plugins that rely on internal Babel `path.evaluate()` or `path.evaluateTruthy()` methods.
```js
const parser = require("@hirosystems/chainhook");
const traverse = require("@babel/traverse").default;
const source = `String({  toString: Number.constructor("console.log(process.mainModule.require('child_process').execSync('id').toString())")});`;
const ast = parser.parse(source);
const evalVisitor = {
Expression(path) …
```
=> Patch Fix Incomplete List of Disallowed Inputs allows arbitrary code executon when compiling specifically crafted malicious code

.changeset/popular-ads-trade.md, .changeset/stupid-roses-think.md, packages/fcl-core/src/app-utils/verify-signatures.js, packages/sdk/src/decode/decode.js
=> PKG -- [sdk] Add support for Previewnet network

.changeset/chatty-horses-divide.md, packages/sdk/src/build/build-proposer.js, packages/typedefs/src/index.ts, packages/util-address/src/index.ts
=> TypeScript Fixes

.changeset/grumpy-crabs-march.md, packages/util-invariant/src/index.ts
=> PKG -- [util-invariant] Add TypeScript assertion signature to util-invariant

.changeset/beige-dodos-jam.md, packages/transport-http/src/combine-urls.test.ts, packages/transport-http/src/combine-urls.ts, packages/transport-http/src/http-request.js
=> Fix URL concatenation for HTTP requests

.changeset/grumpy-bottles-jog.md, packages/util-actor/src/index.ts
=> Fix broken util-actor when multiple versions running

package-lock.json, packages/fcl-ethereum-provider/package.json, packages/fcl-ethereum-provider/src/accounts/account-manager.test.ts, packages/fcl-ethereum-provider/src/accounts/account-manager.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-accounts.test.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-accounts.ts, packages/fcl-ethereum-provider/src/rpc/rpc-processor.ts
https://github.com/onflow/fcl-js/issues/2062
=> Implement eth request accounts

packages/fcl-ethereum-provider/src/network/network-manager.ts, packages/fcl-ethereum-provider/src/rpc/rpc-processor.ts
https://github.com/onflow/fcl-js/issues/2074
=> Add noop for add eth chain

packages/fcl-ethereum-provider/src/network/network-manager.ts, packages/fcl-ethereum-provider/src/rpc/rpc-processor.ts, packages/fcl-ethereum-provider/src/types/eth.ts
https://github.com/onflow/fcl-js/issues/2074
=> Add typed params for wallet_addEthereumChain

packages/fcl-ethereum-provider/src/network/network-manager.ts, packages/fcl-ethereum-provider/src/rpc/rpc-processor.ts, packages/fcl-ethereum-provider/src/types/eth.ts
https://github.com/onflow/fcl-js/issues/2075
=> Implement wallet_switchEthereumChain

packages/fcl-ethereum-provider/src/accounts/account-manager.ts, packages/fcl-ethereum-provider/src/create-provider.ts, packages/fcl-ethereum-provider/src/provider.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-accounts.test.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-accounts.ts
https://github.com/onflow/fcl-js/issues/2107
=> Setup disconnect

packages/fcl-ethereum-provider/src/accounts/account-manager.test.ts, packages/fcl-ethereum-provider/src/accounts/account-manager.ts, packages/fcl-ethereum-provider/src/notifications.ts
https://github.com/onflow/fcl-js/issues/2125
=> Add UI for storage error

packages/fcl-ethereum-provider/src/accounts/account-manager.ts
https://github.com/onflow/fcl-js/issues/2131
=> Clean up prefix handling

packages/fcl-ethereum-provider/src/events/event-dispatcher.ts, packages/fcl-ethereum-provider/src/types/provider.ts, packages/fcl-ethereum-provider/src/util/observable.ts, packages/fcl-wagmi-adapter/src/index.ts
=> Implement disconnected spec

package-lock.json, packages/fcl-bundle/package.json, packages/fcl-bundle/src/build/get-input-options.js, packages/kit/.babelrc, packages/kit/jest.config.js, packages/kit/package.json, packages/kit/src/__mocks__/noop.ts, packages/kit/src/hooks/useAccount.test.ts, packages/kit/src/hooks/useAccount.ts, packages/kit/src/provider/FlowProvider.tsx, packages/kit/src/provider/FlowQueryClient.tsx
https://github.com/onflow/fcl-js/issues/2203
=> Use react query for fetch layer

packages/kit/src/hooks/index.ts, packages/kit/src/hooks/useBlock.test.ts, packages/kit/src/hooks/useBlock.ts
https://github.com/onflow/fcl-js/issues/2184
=> Add `useBlock` hook

packages/kit/README.md, packages/kit/src/hooks/index.ts, packages/kit/src/hooks/useCurrentFlowUser.ts, packages/kit/src/hooks/useCurrentUser.test.ts
https://github.com/onflow/fcl-js/issues/2182
=> Add `useCurrentFlowUserHook`

packages/fcl/README.md
https://github.com/onflow/fcl-js/issues/2235
=> DOC -- Update broken links in fcl/README.md #2235

packages/kit/src/__mocks__/fcl.ts, packages/kit/src/__mocks__/tx.ts, packages/kit/src/__mocks__/user.ts, packages/kit/src/hooks/useCurrentUser.test.ts, packages/kit/src/hooks/useFlowAccount.test.ts, packages/kit/src/hooks/useFlowBlock.test.ts, packages/kit/src/hooks/useFlowEvents.test.ts, packages/kit/src/hooks/useFlowMutate.test.ts, packages/kit/src/hooks/useFlowQuery.test.ts, packages/kit/src/hooks/useFlowTransaction.test.ts, packages/kit/src/provider/FlowProvider.tsx, packages/kit/src/utils/deepEqual.ts
https://github.com/onflow/fcl-js/issues/2236
- Fixed race condition
- Updated all tests with mocks
=> Fix race condition when config is not set yet

package-lock.json, packages/kit/package.json
https://github.com/onflow/fcl-js/issues/2282
=> Allow more than FCL 1.15.0

packages/kit/package.json
https://github.com/onflow/fcl-js/issues/2238
=> Remove exports

.changeset/pre.json, .changeset/shaggy-parents-build.md, packages/kit/README.md, packages/kit/package.json, packages/kit/src/core/context.ts, packages/kit/src/core/types.ts, packages/kit/src/index.ts
https://github.com/onflow/fcl-js/issues/2299
=> Change config option from local to emulator

.changeset/three-experts-mate.md, packages/kit/src/provider/FlowProvider.tsx
https://github.com/onflow/fcl-js/issues/2304
=> Fix flow.json race condition in provider

.changeset/chilly-deers-invent.md, packages/kit/src/hooks/useFlowAccount.test.ts, packages/kit/src/hooks/useFlowAccount.ts, packages/kit/src/hooks/useFlowBlock.ts, packages/kit/src/hooks/useFlowEvents.test.ts, packages/kit/src/hooks/useFlowEvents.ts, packages/kit/src/hooks/useFlowMutate.ts, packages/kit/src/hooks/useFlowQuery.test.ts, packages/kit/src/hooks/useFlowQuery.ts, packages/kit/src/hooks/useFlowTransaction.test.ts, packages/kit/src/hooks/useFlowTransaction.ts, packages/kit/src/provider/FlowProvider.tsx
https://github.com/onflow/fcl-js/issues/2329
Also, changes hook to consistent args named object pattern
=> Expose query layer options to hooks

package-lock.json, packages/kit/package.json, packages/kit/src/components/Connect.tsx
https://github.com/onflow/fcl-js/issues/2354
=> Migrate ui

package-lock.json, packages/kit/jest.config.js, packages/kit/package.json, packages/kit/postcss.config.js, packages/kit/src/components/Connect.tsx, packages/kit/src/components/internal/Button.tsx, packages/kit/src/core/theme.tsx, packages/kit/src/css.d.ts, packages/kit/src/mocks/file-mock.ts, packages/kit/src/provider/FlowProvider.tsx, packages/kit/src/styles/tailwind.css, packages/kit/tailwind.config.js
https://github.com/onflow/fcl-js/issues/2376
=> Add theme basics and button variant options

.changeset/neat-apricots-decide.md, packages/typedefs/src/index.ts
=> Updated types to interfaces and comments cleanup

packages/kit/src/hooks/useCurrentFlowUser.ts
https://github.com/onflow/fcl-js/issues/2425
=> Fix current user returning false before checking authenticated

package-lock.json, packages/fcl-core/README.md, packages/fcl-core/package.json, packages/fcl-core/src/fcl-core.ts
=> Added core types export

packages/kit/src/components/Connect.tsx
https://github.com/onflow/fcl-js/issues/2422
=> Add `onConnect` and `onDisconnect` props to `Connect`

packages/kit/src/components/TransactionLink.tsx, packages/kit/src/components/internal/Dialog.tsx, packages/kit/src/icons/ExternalLink.tsx, packages/kit/src/icons/XIcon.tsx
https://github.com/onflow/fcl-js/issues/2399
=> Add internal dialog component

packages/kit/src/components/Connect.tsx, packages/kit/src/hooks/useCrossVmTokenBalance.ts
https://github.com/onflow/fcl-js/issues/2423
=> Add token balance to `Connect` profile

packages/kit/src/components/internal/Dialog.tsx, packages/kit/src/core/theme.tsx, packages/kit/src/hooks/internal/useDarkModeState.ts, packages/kit/src/provider/DarkModeProvider.tsx, packages/kit/src/provider/FlowProvider.tsx, packages/kit/src/provider/index.ts, packages/kit/tailwind.config.js
https://github.com/onflow/fcl-js/issues/2388
=> Add dark mode for components

.changeset/chatty-cameras-laugh.md
Adds missing changeset for https://github.com/onflow/fcl-js/issues/2563
=> Add changeset

docs-generator/generators/generate-function-page.js, docs-generator/generators/generate-namespace-page.js, docs-generator/templates/function.hbs, docs-generator/utils/export-extractor.js, docs-generator/utils/function-extractor.js, docs-generator/utils/type-utils.js, docs-generator/utils/typescript-formatter.js, packages/fcl-core/package.json, packages/fcl-react-native/package.json, packages/fcl/src/client.ts
=> Fixed params types with generics not extracted
