packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/resolve-signatures.js
PKG -- [sdk] Allows authorizer payer and proposer to be the same acct
=> PKG -- [sdk] Allows authorizer payer and proposer to be the same acct

packages/protobuf/CHANGELOG.md, packages/protobuf/src/generated/flow/access/access_pb.d.ts, packages/protobuf/src/generated/flow/access/access_pb.js, packages/protobuf/src/generated/flow/execution/execution_pb.d.ts, packages/protobuf/src/generated/flow/execution/execution_pb.js, packages/protobuf/src/proto/flow/access/access.proto, packages/protobuf/src/proto/flow/execution/execution.proto
Work towards dapperlabs/flow-go#3068.
Depends on https://github.com/onflow/flow/pull/20.
Update access proto, adding `Arguments` field to script requests. This is work towards implementing script params as described in the above issue.
I believe you two have opinions about how to proceed with backwards compatibility by supporting both means of passing in parameters, so I just wanted to open up this PR in the interim.
=> Provide support for script arguments

packages/fcl/src/current-user/render-frame.js
Currently there's a white border around Authn/Authz iframes which can look strange especially for dApps with dark background.
I think the overall look and feel for dApps + wallet can be improved without this border.
=> Remove authn/authz iframe border

packages/rlp/src/index.js
removing exports as it hinders with importing the library as Stencil component.
=> fixing rlp exports issue on get length

packages/sdk-resolve-signatures/src/index.js, packages/send/src/send-transaction.js
Currently for the case of multi-sig accounts, if we need multiple authorizer signatures from the same account, we need to do this:
```javascript
fcl.authorizations([
authorization1, // acc1, key1
authorization2, // acc1, key2
]),
```
but when the payload is encoded, it resolves into multiple authorizers with the same address
`authorizers:['acc1_address', 'acc1_address']`
and results in transaction failure
while it should be deduplicated into
`authorizers:['acc1_address']`
This PR fixes this issue.
=> Fix when multiple authorizer have same address

packages/fcl/src/temp.js
For example, in the case that user requires authorization from 2 accounts `["account1", "account2"]` and `account1` requires 2 keys `["account1|0", "account1|2"]`, authorizers are mapped from 
```
["zxxsf8uvs7", "mf0v3p6t2c"]
->
["CURRENT_USER", "mf0v3p6t2c"]
->
[ ["0xd5f1a3954f06b231|0", "0xd5f1a3954f06b231|2"], "mf0v3p6t2c"]
->
["0xd5f1a3954f06b231|0", "0xd5f1a3954f06b231|2", "mf0v3p6t2c"]
```
Mutate key ID with the key ID from signature response.
=> Updates for pre-auth - multiple keys from the same account

packages/fcl/src/resolvers/resolve-signatures.js
This seems to be dropped accidentally during the cleanup! https://github.com/onflow/flow-js-sdk/commit/6e33da8627a6f2411d333aac7aa316200f3861e1
=> Use keyID from signatures

packages/sdk/CHANGELOG.md, packages/sdk/src/build/build-params.js, packages/sdk/src/build/build-params.test.js, packages/sdk/src/interaction/interaction.js, packages/sdk/src/resolve/resolve-cadence.test.js, packages/sdk/src/sdk.js, packages/sdk/src/utils/index.js
Remove files, functions, and references to params for deprecation.
- rm build-params.js
- delete makeParams from interaction
- remove exports from sdk/fcl
- clean up tests
=> [sdk] Remove build-params and makeParams

packages/sdk/CHANGELOG.md, packages/sdk/src/wallet-utils/index.js, packages/sdk/src/wallet-utils/validate-tx.js, packages/sdk/src/wallet-utils/validate-tx.test.js
- Adds `sdk.wallet-utils.validateSignableTransaction` 
- Support for wallets to validate `Signable` transaction `message` against `voucher`
=> [sdk] Add wallet-utils and validateSignableTransaction

packages/sdk/CHANGELOG.md, packages/sdk/src/interaction/interaction.js, packages/sdk/src/resolve/resolve-accounts.js, packages/sdk/src/resolve/resolve-signatures.js, packages/sdk/src/utils/create-voucher.js, packages/sdk/src/utils/index.js
- Move/rename `createVoucher` to /utils to resolve circular dependency in `interaction`
=> [sdk] Move createVoucher to /utils

packages/fcl/README.md
Currently the table format that is read by github does not show up on NPM (https://www.npmjs.com/package/@onflow/fcl) and makes it look weird. This would fix that but unsure if this violating any standard format.
Changes:
---
title: FCL
description: Making secure web applications powered by the Flow Blockchain
---
to
=> Tiny fix: Update README.md readability on NPM

packages/fcl/CHANGELOG.md, packages/fcl/src/fcl.test.js, packages/fcl/src/serialize/index.js
- Exposes `createSignableVoucher` from `sdk`
- Updates `serialize` to return serialized `voucher` instead of `interaction`
=> [fcl] Updates serialize to return serialized voucher

README.md, packages/sdk/readme.md
- noticed one of the links to `responses` was broken
- noticed Example 4 & Example 5 had the same title but were different types of `Interactions`
- fixed some minor grammar things with `Resolves` -> `Resolve` & `using` -> `use`
=> [docs] update broken readme link

packages/sdk/CHANGELOG.md, packages/sdk/src/send/unary.js
[sdk] -- Adds ability to specify optional grpc metadata to requests sent to an Access API
=> [sdk] -- Adds ability to specify optional grpc metadata to requests sent to an Access API

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/strategies/http-post.js, packages/fcl/src/current-user/exec-service/strategies/iframe-rpc.js, packages/fcl/src/current-user/index.js, packages/fcl/src/current-user/normalize/composite-signature.js
`verifyUserSignatures` returns true if the given signatures are valid for the given signed data
- Adds `verifyUserSignatures` util to `currentUser()` 
- Refines use of `composite-signature` normalization
=> [fcl] Add verifyUserSignatures util to currentUser

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js, packages/fcl/src/serialize/index.js
- Add missing `await` on auth endpoint config
- Update `fcl.serialize` to use new config.first in setting `resolveFunction`
=> [fcl] Update serialize to use new config util

packages/sdk/CHANGELOG.md, packages/sdk/src/resolve/__snapshots__/resolve-signatures.test.js.snap, packages/sdk/src/resolve/resolve-accounts.test.js, packages/sdk/src/resolve/resolve-signatures.js, packages/sdk/src/resolve/resolve-signatures.test.js
Update how payload sigs are returned in `createSignableVoucher`
- Build and return `payloadSigs` and `envelopeSigs` separately
- Fixes CORS bug
=> [sdk] Update how payload sigs are returned from createSignableVoucher

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
- Updates `fcl.verifyUserSignature` to pass account publicKey signingAlgos as `Uint` into Cadence script. Allows for successful verification of supported algorithms `ECDSA_P256` and `ECDSA_secp256k1`
=> [fcl] Updates verifyUserSignature to include publicKey signingAlgorithms

packages/sdk/CHANGELOG.md, packages/sdk/src/send/send-execute-script.js, packages/sdk/src/send/send-execute-script.test.js, packages/sdk/src/send/send-get-account.js, packages/sdk/src/send/send-get-account.test.js, packages/sdk/src/send/send-get-block-header.js, packages/sdk/src/send/send-get-block-header.test.js, packages/sdk/src/send/send-get-block.js, packages/sdk/src/send/send-get-block.test.js, packages/sdk/src/send/send-get-collection.js, packages/sdk/src/send/send-get-collection.test.js, packages/sdk/src/send/send-get-events.js, packages/sdk/src/send/send-get-events.test.js, packages/sdk/src/send/send-get-transaction-status.test.js, packages/sdk/src/send/send-get-transaction.test.js, packages/sdk/src/send/send-transaction.test.js
[sdk] -- Refactors Send Functions to prevent and mitigate cases where the expected request type cannot be determined.
@psiemens : This PR addresses the concerns raised in https://github.com/onflow/flow-js-sdk/pull/714 , as well as propagates the new pattern of splitting up the various individual send functions for each AccessAPI method out of each exported send function.
=> [sdk] -- Refactors Send Functions to prevent and mitigate cases where the expected request type cannot be determined.

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
- Updates `verifyUserSignatures` to use `account` util from `@onflow/sdk`
=> [fcl] Quickfix for verifyUserSignatures

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/index.js, packages/fcl/src/current-user/exec-service/strategies/iframe-rpc.js, packages/fcl/src/current-user/exec-service/strategies/pop-rpc.js, packages/fcl/src/current-user/index.js, packages/fcl/src/fcl.js
- Adds use of `discovery.wallet.view` to configure `authn` view
=> [fcl] Update to revert default authn/authz method/view

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/index.js, packages/fcl/src/current-user/exec-service/strategies/iframe-rpc.js, packages/fcl/src/current-user/exec-service/strategies/pop-rpc.js, packages/fcl/src/current-user/exec-service/strategies/utils/pop.js, packages/fcl/src/current-user/index.js, packages/fcl/src/current-user/normalize/polling-response.js, packages/fcl/src/default-config.js
- Update all calls to `execService` with parameter destructuring.
- Move `authn` config to iframe/pop body
- Add new `discovery.wallet.method` config
=> [fcl] Update currentUser.authenticate and execService

.prettierignore, docs/api.md, docs/user-signature.mdx
=> [root] Update API Reference with user-signature methods

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/strategies/pop-rpc.js, packages/fcl/src/current-user/exec-service/strategies/tab-rpc.js
- Sends deprecated `FCL:FRAME:READY:RESPONSE` `in pop-rpc`, `tab-rpc`
=> [fcl] Update pop/tab frame onReady response

docs/api.md
Small typo in API docs, just wanted to put up the fix.
=> Fix Typo in API Docs

packages/fcl/CHANGELOG.md, packages/fcl/src/wallet-provider-spec/draft-v3.md, packages/fcl/src/wallet-utils/CompositeSignature.js, packages/fcl/src/wallet-utils/index.js, packages/fcl/src/wallet-utils/wallet-utils.test.js
- Add `WalletUtils.CompositeSignature`
- Update wallet-provider spec
=> [fcl] Add CompositeSignature constructor to WalletUtils

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
As noted in [this issue](https://github.com/onflow/fcl-js/issues/709), people are confused by having to get the current user via  a function. Instead, they'd expect it to be an object. This PR does the following:
- Simplifies `currentUser` syntax to be accessed as an object. For example, this will allow you to write `currentUser.snapshot()` instead of `currentUser().snapshot()`.
- Keeps supporting the existing way to obtaining the current user with `currentUser()`
Addresses issue: https://github.com/onflow/fcl-js/issues/709
=> PKG -- [fcl] Simplify currentUser syntax

packages/fcl/src/config-utils.js, packages/fcl/src/current-user/index.js
There is no warning if someone tries to use `currentUser` on the server side (for example, see this issue: https://github.com/onflow/fcl-js/issues/803#issuecomment-926905178). This adds a warning that `currentUser` is not available with a window check and links the docs.
Also, set storage to false for local and session storage if it's not the browser.
=> PKG -- [fcl] warn if currentUser is being used server side

packages/sdk/CHANGELOG.md, packages/sdk/src/interaction/interaction.js, packages/sdk/src/resolve/resolve-arguments.js, packages/sdk/src/resolve/resolve-arguments.test.js
SDK changes to address feedback in this PR: https://github.com/onflow/fcl-js/pull/811
Changing the resolve arguments step to use more specific method naming as opposed to a generic resolve method.
=> PKG -- [sdk] Resolve argument with specific resolveArgument method

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/build-user.js
=> [fcl] Update buildUser data

packages/fcl/src/exec/verify.js
In some specific hardware key environments, SHA3_256 is not included. However, fcl uses SHA3_256 as the *only* hash algorithm when verifying user message and signature. 
The hash algorithm bound to the key for user signature verification will be a better choice.
=> [fcl][verify] adopt hash algo by key's hash algo

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/index.js
- Dedupe accounts and limit multiple calls to authz/authn
- Remove user `notExpired` check as always `false` due to Blocto returning past unix timestamp
=> [fcl] Update authz to dedupe accounts

packages/fcl/CHANGELOG.md, packages/fcl/src/config-utils.js, packages/fcl/src/discovery/services.js, packages/fcl/src/discovery/services.test.js
Add `include` filtering support for `discovery.wallet`. Addresses: https://github.com/onflow/fcl-js/issues/899
Creates required params for routing to `discovery.wallet` if `discovery.authn.include` is set in config.
=> PKG -- [fcl] Support include filtering for discovery.wallet

packages/fcl/src/current-user/exec-service/strategies/utils/render-frame.js
Use `100%` instead of `100vh` to accommodate for URL bar.
Reference: https://stackoverflow.com/a/59020698
100%
100vh
=> Refine FCL iframe display in mobile

packages/fcl/CHANGELOG.md, packages/fcl/src/exec/__tests__/verify-usig.test.js, packages/fcl/src/exec/verify.js
- Adds validation to enforce signatures need to be from a single account address
- Removes extra script to get account keys by moving into script
- Updates Cadence query script
- Deals with getting account key, and enforces no duplicate keys
- Adds key weight threshold
=> [fcl] Updates `fcl.verifyUserSignatures`

docs/reference/api.md
in the authenticate section, the internal link to discovery is written in the incorrect format of Markdown link.
https://docs.onflow.org/fcl/reference/api/#authenticate
=> fix broken internal link in reference/api.md doc

docs/reference/api.md
anchor link to account object is set wrong path.
https://docs.onflow.org/fcl/reference/api/#getaccount
=> fix anchor path for account object

packages/fcl/CHANGELOG.md, packages/fcl/src/config-utils.js, packages/fcl/src/current-user/index.js, packages/fcl/src/current-user/normalize/authn-refresh.js, packages/fcl/src/current-user/normalize/service.js
There was no way to know if a user’s wallet provider session had expired or ended for other reasons.
This led to a situation where a user who is logged in to an app initiates a transaction which fails silently and without any clear error. The user needs to reauthenticate, but the client (and FCL) were unaware. 
Wallet Providers can now provide an optional **Authentication Refresh Service** to FCL upon initial configuration.
If provided, FCL will attempt to refresh the user's session by executing this service before a transaction.
This solution provides a standard way for the app to reauthenticate a user or inform them that their wallet session has expired.
FCL will use the `authn-refresh` service endpoint and method provided to request updated authentication data from the Wallet Provider. …
=> [fcl] Adds optional Authentication Refresh Service to `fcl.authenticate`

README.md, docs/index.mdx, docs/tutorials/flow-app-quickstart.mdx
use relative links whenever possible in documentation so that when readers clicks the link in Github, they will be directed to Github pages; when readers click the link in docs.onflow.org, they will be directed to Flow doc site pages
Our official doc site can not handle relative linking well in the past, however, we recently addressed that (https://github.com/onflow/flow/issues/704) so that we can write relative paths in Markdown (or .mdx) files.
=> use relative link when referring to FCL documents

SECURITY.md
There was some weird space formatting finding its way into the security doc, as well as missing punctuation at the end of the last sentence. This small PR tidies that up a bit.
=> Update space formatting in security doc, adds period at end of line

docs/tutorials/flow-app-quickstart.mdx
Hi, as discussed/suggested in https://github.com/onflow/fcl-js/issues/934, I ported the FCL quickstart to Next.js. 
What changed:
- I kept the same bare-bones approach (i.e. no fancy transaction components, no big abstractions)
- HOWEVER, I added some links at the top of the Quickstart to point to some more polished, ready to go templates/samples made by the community (i.e. a link to the FCL section of [Get The Flow Down](https://github.com/ph0ph0/Get-The-Flow-Down) by @ph0ph0).
=> Changed quickstart to Next.js

docs/reference/api.md
You can now access `currentUser` methods from an object rather than needing to invoke a function. This PR updates docs to change references `currentUser().method` to `currentUser.method`.
=> DOC -- [root] Update current user syntax on docs

packages/fcl/CHANGELOG.md, packages/fcl/src/current-user/exec-service/strategies/ext-rpc.js, packages/fcl/src/current-user/exec-service/strategies/utils/extension.js, packages/fcl/src/current-user/exec-service/strategies/utils/render-ext.js
- When executed posts msg `type: "FCL:LAUNCH:EXTENSION"` and sets up listener for communication with browser extension.
- Extension should listen for msg `type: "FCL:LAUNCH:EXTENSION"` to enable ext/open popup window, and respond with `"FCL:VIEW:READY"`
- FCL will respond with `"FCL:VIEW:READY:RESPONSE"` type and service data, and wait for `PollingResponse`
=> [fcl] Update extension strategy

docs/reference/api.md
Hi, 
Noticed that in the doc it was coded as `login` instead of `logIn`. After researching the docs commit history, I saw that this was added in #729 and not changed since then. 
It was not working in my authentification, and was resolved using the correct casing. 
Hope to save some time to someone :)
=> DOC -- [root] Fix logIn casing

packages/fcl/src/current-user/exec-service/index.js
More client metadata needs to be sent. We want to keep it set from configurable app data in a new object called `client`. Currently, in here we will send the library used to send the data, fcl version, and the hostname of the app sending the data.
Addresses: 
- https://github.com/onflow/fcl-js/issues/1029
- https://github.com/onflow/fcl-js/issues/1030
=> Send FCL client config data

CODEOWNERS, packages/sdk/CHANGELOG.md, packages/sdk/src/interaction/interaction.js, packages/sdk/src/utils/deprecate.js, packages/sdk/src/utils/logger.js
Addresses: https://github.com/onflow/fcl-js/issues/1046
----
This is the first step in property renamings/deprecations mentioned on the ticket above. We want to give notices to developers to change to the new names, but we first need to change our internal usage before these notices go fully live. This PR adds a way to enable warnings if a config for logger is set to the corresponding level. If a developer enables this they will see it. Once we have changed our usage internally, we can remove the logging level so that it warns any time it is used. 
It does not modify the account or interaction object. Instead, it uses a proxy to return the original properties' value if either the original property or the new property is being used. If it is the original property being used, then the …
=> PKG -- [sdk] Setup field renamings/deprecations

README.md
Hi!
We are considering adding Flow Dapp support to our wallet, and first of all I just want to confirm that if we develop it, we will be able to just add it in https://github.com/onflow/fcl-discovery/blob/master/data/services.json. If the process is not as I described (making a PR there), but something else, let's discuss it, and I will modify this PR to include that process description in the readme.
I also had a hard time finding the `fcl-discovery` repo itself, so I think it would be useful for others as well to link it here.
=> DOC -- [root] Add links to the fcl-discovery repo in the readme

packages/transport-http/src/http-request.js
Fix a bug that causes `fetchTransport` to be undefined in environments where `fetch` is defined but `window` isn't (e.g. Cloudflare Workers)
Resolves #1089
=> PKG -- [transport-http] Preference `fetch` over `window?.fetch`

packages/sdk/CHANGELOG.md, packages/sdk/package-lock.json, packages/sdk/package.json, packages/sdk/src/resolve/resolve-proposer-sequence-number.js, packages/sdk/src/resolve/resolve-ref-block-id.js, packages/sdk/src/resolve/resolve.js, packages/sdk/src/send/send.js
PKG -- [sdk] Makes @onflow/transport-http the default send module used by sdk
=> PKG -- [sdk] Makes @onflow/transport-http the default send module used by sdk

.changeset/heavy-cats-draw.md, docs/reference/api.md, packages/fcl/src/app-utils/__tests__/verify-user-sig.test.js, packages/fcl/src/app-utils/index.js, packages/fcl/src/app-utils/verify-account-proof.js, packages/fcl/src/app-utils/verify-user-signatures.js, packages/fcl/src/current-user/index.js, packages/fcl/src/exec/verify.js, packages/fcl/src/utils/deprecate.js, packages/fcl/src/utils/index.js, packages/fcl/src/wallet-utils/encode-account-proof.js
- Remove deprecated `currentUser.verifyUserSignatures`
- Deprecate `fcl.verifyUserSignatures`
- Update api reference doc
=> [fcl] Move verifyUserSignatures to AppUtils

.changeset/short-ravens-return.md, docs/reference/api.md, packages/fcl/src/app-utils/verify-signatures.js
`AppUtils.verifyAccountProof` and `AppUtils.verifyUserSignatures` now require
setting `fcl.config.flow.network` (testnet or mainnet) or override contract address via
`opts.fclCryptoContract`
=> [fcl] Update verifyAccountProof verifyUserSignatures

.changeset/good-cougars-impress.md, packages/fcl/src/current-user/exec-service/index.js
In execService, removes adding window.extensions on msg passed to Discovery.
This is now added to `config`
=> [fcl] Remove window.extensions from service msg

.changeset/rotten-news-scream.md, packages/config/package.json, packages/fcl/package.json, packages/rlp/package.json, packages/sdk/package.json, packages/transport-grpc/package.json, packages/transport-http/package.json, packages/types/package.json, packages/util-actor/package.json, packages/util-address/package.json, packages/util-encode-key/package.json, packages/util-invariant/package.json, packages/util-logger/package.json, packages/util-node-http-modules/package.json, packages/util-template/package.json, packages/util-uid/package.json
Watch scripts were still compressing.  Easier to debug non-minified files. `--define MICROBUNDLE_CURRENT_VERSION=$npm_package_version` was missing altogether from @onflow/fcl watch script and was required to run `npm run watch`
=> OPS -- Add '--no-compress' to watch scripts

.changeset/nasty-actors-sing.md, packages/fcl/src/transaction/index.js
This was being caused by unhandled network exception in the POLL handler for the transaction subscriber.  When this exception was thrown (i.e. server error, user network disconnect on shoddy network perhaps *potential issue for those on mobile networks*), it would abort the POLL handler prior to `setTImeout(() => ctx.sendSelf(POLL), RATE)` being called, effectively ending the POLL prematurely.
This may be a recurring issue with actors that likely follow the same pattern and stop polling after a single unhandled exception.
=> PKG -- [fcl] Handle network disconnect in transaction subscriber

.changeset/chilled-vans-happen.md, packages/transport-http/src/send-get-transaction-status.js, packages/transport-http/src/send-get-transaction-status.test.js
Changed 1 line of code and started using status_code from http response for transaction status polling.  Was marked as a TODO for when the HTTP API supported it.  Prettier butchered the file.
=> PKG -- [transport-http] Add status code to transaction status

.changeset/itchy-pumpkins-dream.md, packages/fcl/src/current-user/exec-service/strategies/utils/extension.js, packages/fcl/src/current-user/exec-service/strategies/utils/frame.js, packages/fcl/src/current-user/exec-service/strategies/utils/pop.js, packages/fcl/src/current-user/exec-service/strategies/utils/tab.js
Fixes a bug where event listener was not being removed on close
- Updates to listeners in iframe, pop, tab, ext to return reference to handler function and use in removeEventHandler on close
=> [fcl] - Update event listeners

.github/workflows/call-refresh-doc.yml
Closes [#67](https://github.com/onflow/next-docs-v1/issues/67)
Create Github Actions in Documentation Sources, aka github repositories:
There are 2 workflows: 1. call-refresh-doc, 2. refresh-doc. First parses the documentation for diffs, and calls the second if there are any.
This repo only has the first workflow, and will call the refresh-doc workflow in /flow https://github.com/onflow/flow/pull/953
Used tj-actions/changed-files@v18.7 to get all the doc files that were edited
Logs more detailed information (added, deleted, modified) for the diff files
Calls the doc site's refresh endpoint located in /flow with the content paths, SHA, and repository name
______
For contributor use:
=> Add github actions for getting diff & calling refresh

packages/types/src/types.js, packages/types/src/types.test.js
This PR makes sure the UFix64 and Fix64 are always extended to include 8 decimal places, that is done in order to ensure output that is unified with how Cadence Go implementation formats the Fix numbers. 
This also closes the issue: https://github.com/onflow/cadence/issues/1652
=> [Types] Extend decimal places for UFix64 and Fix64

.changeset/hungry-otters-relate.md, packages/fcl/src/app-utils/verify-signatures.js
- Indices passed in as Numbers changed to Strings
- Passing in Number as value for Int is deprecated
=> [fcl] Updates keyIndices args passed in as Numbers

packages/fcl/src/wallet-provider-spec/draft-v3.md, packages/fcl/src/wallet-provider-spec/draft-v4.md
I recommend reviewing the two commits separately:
- DOC -- [fcl] Fix some typos in draft-v3.md
- DOC -- [fcl] Add schema and more precise protocol description
The first one just fixes some typos, while the second one contains a lot of new content.
**Motivation**
The spec currently has a number of issues. This PR improves by
1. properly specifying the schema of the objects used in the protocols, and
2. making the description of the `EXT/RPC` service method more precise.
There are still many improvements that could be done, including
- Checking that the schema is really exhaustive, I might have missed some objects.
- Completing the schema. I used some `unknown` types at some places, and didn't properly complete every description. A number of the descriptions I included are not precise …
=> Improve the wallet provider spec

.changeset/curly-brooms-marry.md, packages/fcl/src/app-utils/__tests__/verify-user-sig.test.js, packages/fcl/src/app-utils/verify-signatures.js
If the `CompositeSignature` being verified does not use `0x` prefix, the script will fail.
This ensures `0x` prefix on addresses for verification.
=> [fcl-js] Ensures 0x prefix on addresses when verifying Composite Signatures 

docs/reference/api.md
The new site interprets everything as MDX so the `{string}` causes a compile error. I changed this to match the other items in the list which don't use brackets and are valid MDX.
=> Make api.md compatible with new docs site

.changeset/eleven-bobcats-complain.md, .changeset/empty-donkeys-trade.md, package-lock.json, packages/transport-http/src/http-request.js, packages/transport-http/src/http-request.test.js
Closes #1363
- Retry 429 responses
- Refactor http-request.js for readability
- Handle empty response body without throwing JSON error
=> PKG -- [transport-http] Retry 429 responses

packages/fcl/src/app-utils/verify-signatures.js
With the expression, `t.Array([t.Int])`, the request queries with an array that only carries the first value of the array that is passed as the argument. This will cause the verification to fail when it needs to verify with multiple signatures.
This fix makes sure the script receives the complete array.
=> PKG -- [fcl] fix arguments' types that are queried along with the signature verification script

docs/index.md, docs/index.mdx, docs/reference/api.md, docs/reference/sdk-guidelines.mdx, docs/tutorials/flow-app-quickstart.mdx
Ran python script from docs root to replace all broken links on new docs site
```python
import os
import re
for root, dirs, files in os.walk('.'):
for f in files:
if not os.path.splitext(f)[1] in [".mdx", ".md"]: continue
with open(os.path.join(root, f),"r+") as file:
lines = [re.sub(r'\[([^\]]*)\]\(([\w\-. ]*\#[\w\d\-]+)\)', r'[\1](./{}\2)'.format(os.path.basename(f)), line) for line in file.readlines()]
file.seek(0)
file.writelines(lines)
```
=> PKG -- [docs] Fix broken links on new docs site

.changeset/afraid-cobras-wash.md, .changeset/great-avocados-knock.md, .changeset/two-dolphins-tan.md, packages/fcl-wc/README.md, packages/fcl-wc/src/fcl-wc.js, packages/fcl-wc/src/fcl-wc.test.js, packages/fcl-wc/src/service.js, packages/fcl-wc/src/utils.js, packages/fcl/src/current-user/exec-service/plugins.js, packages/fcl/src/current-user/index.js, packages/fcl/src/discovery/services.js, packages/fcl/src/discovery/services/authn.js, packages/fcl/src/discovery/utils.js
This PR updates the WalletConnect adapter API, and service plugin returned. It improves Discovery (UI/API) integration by sending strategies supported by the client.
- `includeBaseWC` (default: false): If true, will include a generic WalletConnect service 
- `sessionRequestHook` (default: null): A function to be called on a Desktop session request so the DApp can inform the user to open and approve in the user's mobile wallet. This will be called if a wallet was previously connected and no QR code scanning is required to pair.
- `wallets` (default: [ ]): **testnet only** The DApp can include an array of wallet services of type `authn`. These will be combined with wallets returned from [WalletConnect cloud registry API](https://cloud.walletconnect.com/), deduped by Service uid and sent to …
=> [fcl][fcl-wc] - Updates to WC adapter API and Discovery Integration

.changeset/young-mice-bow.md, packages/fcl/src/discovery/services/authn.js
Looks like page loaded before event listeners are added in Safari. Seems to be an issue with server side rendered apps.
Addresses: https://github.com/onflow/fcl-discovery/issues/106
=> Discovery API not loading on SSR apps in Safari and Incognito

.changeset/lazy-poets-return.md, packages/fcl-wc/src/constants.js, packages/fcl-wc/src/fcl-wc.js, packages/fcl-wc/src/service.js, packages/fcl-wc/src/utils.js
- Improves deeplinking for pairing and requests on mobile and provides `wcRequestHook` for dApp to alert user of signing request
- Adds additional options to init for pairing modal override
```js
import * as fcl from '@onflow/fcl'
import { init } from '@onflow/fcl-wc'
// example using pairing data from wcRequestHook and providing a custom pairing modal
const { FclWcServicePlugin, client } = await init({
projectId: PROJECT_ID,
metadata: PROJECT_METADATA,
includeBaseWC: false,
wallets: [],  
wcRequestHook: (data: WcRequestData) => {
const peerMetadata = data?.pairing?.peerMetadata
setSessionRequestData(peerMetadata)
setShowRequestModal(true)
},
pairingModalOverride: (uri: string = '', rejectPairingRequest: () => void) => {
openCustomPairingModal(uri)
// call rejectPairingRequest() to …
```
=> [fcl-wc] add pairing modal override and sessionRequestHook

.changeset/serious-spies-remember.md, packages/fcl/src/current-user/exec-service/index.js, packages/fcl/src/current-user/index.js
=> [fcl] move base config to execService and combine with authn config

README.md
Flow App Quick Start URL returns a 404 page:
Updated to the up-to-date correct URL: https://developers.flow.com/tools/fcl-js/tutorials/flow-app-quickstart
=> docs(README): update Flow App Quick Start url

README.md
The zed io one is outdate and deprecated, update with outblock repo link ：）
=> Update fcl iOS link

.changeset/empty-experts-complain.md, packages/fcl/src/current-user/index.js
This patch adds back `discoveryAuthInclude` as part of config.client sent to discovery
=> [fcl] Send discovery include as part of authn client config

.changeset/seven-ears-glow.md, .gitignore, packages/rlp/src/index.js
@onflow/rlp package has `encode` but no `decode`
Tasks:
1. Remove unused decode method that takes input and stream
2. Rename old _decode and export rlp decode
Was successful in testing using `npm link` with flow port.
Addresses feature request
https://github.com/onflow/fcl-js/issues/1472
=> export rlp decode

.changeset/gorgeous-eagles-invent.md, packages/fcl/src/current-user/index.js
Account proof resolver was being called even when a user was already authenticated. This was unnecessary and could
lead to pop up blocking on authz/user-signature requests.
- Adds check and log warning if resolver is not an async function
=> [fcl] Update account proof resolver to only call on authn

.changeset/tiny-lies-cheer.md, packages/fcl-wc/src/constants.js, packages/fcl-wc/src/fcl-wc.js, packages/fcl-wc/src/service.js, packages/fcl-wc/src/utils.js
- Adds `flow_pre_authz` to requiredNamespaces
- Removes constraint for test/mainnet only allowing for dev of emulator wallets
=> [fcl-wc] - Adds support for pre-authz method

packages/transport-http/src/send-get-block-header.js, packages/transport-http/src/send-get-block-header.test.js
GetBlockHeader should send "height=final" instead of "height=finalized" based on https://github.com/onflow/flow-go/blob/6a817aabdf58011ffc917bd6b2335160bff7793f/engine/access/rest/request/height.go#L10
=> PKG -- [transport-http] Fix getBlockHeader

.changeset/warm-schools-jump.md, packages/sdk/src/resolve/resolve-cadence.js, packages/sdk/src/resolve/resolve-cadence.test.js
The addresses in flow.json are not guaranteed to be prefixed with a `0x` but they are needed for valid scripts and transactions.
=> Ensure zero x prefix

.changeset/modern-goats-drum.md, packages/fcl/src/current-user/exec-service/strategies/utils/service-endpoint.js, packages/transport-grpc/src/send-transaction.js, packages/transport-http/src/send-transaction.js
prep work for #1593
in React Native we need to check `window` and `CustomEvent` for existence explicitly otherwise it errors out with an error
=> PKG -- [fcl] additional web checks

.changeset/unlucky-pugs-battle.md, packages/fcl/src/current-user/exec-service/strategies/utils/poll.js
PKG -- [fcl] Retry on network error is page is not visible during backchannel polling
Closes: https://github.com/onflow/fcl-js/issues/1582
=> PKG -- [fcl] Retry on network error is page is not visible during backchannel polling

docs/index.md
in line no 149 :- FCL is agnostic to the communication channel and  `be`  -> `is` configured to
=> made minor grammatical corrections in the docs

packages/fcl/src/current-user/index.js
#1642 
Fixing return type definition of `signUserMessage`
=> PKG -- [fcl/typedefs] Fix return type #1642

.changeset/selfish-parents-argue.md, packages/fcl/src/current-user/exec-service/strategies/utils/poll.js
PKG -- [fcl] Skip network requests when polling on service if document is not visible
Closes: https://github.com/onflow/fcl-js/issues/1582#issuecomment-1521623365 https://github.com/onflow/fcl-js/issues/1634
=> PKG -- [fcl] Skip network requests when polling on service if document is not visible

.changeset/polite-moons-study.md, packages/fcl/src/default-config.js, packages/fcl/src/utils/chain-id-watcher.js, packages/fcl/src/utils/chain-id-watcher.test.js, packages/fcl/src/utils/get-chain-id.js, packages/fcl/src/utils/get-chain-id.test.js, packages/fcl/src/utils/index.js
=> Fixed getChainIdDefault() race condition

package-lock.json, packages/fcl-wc/package.json, packages/fcl/package.json
Addresses: https://github.com/onflow/fcl-js/issues/1653
----------
We were running into this issue https://github.com/nodejs/node/issues/47563.  Removing the "window" global appears to be sufficient to fix this.
=> Fix Jest on node v18.16.0

packages/typedefs/src/index.js
Fixed typo in type definitions
=> OPS -- [typedefs] fixed typo

.changeset/tasty-shirts-flow.md, packages/fcl/src/current-user/exec-service/strategies/utils/service-endpoint.js, packages/fcl/src/current-user/fetch-services.js, packages/fcl/src/current-user/url-from-service.js, packages/fcl/src/discovery/services.js, packages/fcl/src/fcl-react-native.js, packages/fcl/src/utils/is-react-native.js, packages/fcl/src/utils/url.js
Closes #1692 
This is a really nasty bug that is affecting the dev wallet currently and potentially other wallets in the future.  See the issue provided for an overview of why these changes are needed.  TLDR: react native violates WhatWG URL standard
I've added a wonky patch to the react-native scaffold for now https://github.com/jribbink/fcl-react-native-scaffold/commit/041d50486c44cc39a1428f15c9cf8a37ef8253b2, but this should be killed ASAP.  Just figured that working with a wonky patch > not working for the interim
=> PKG -- [fcl] Patch URL trailing slash behaviour in React Native

.changeset/warm-dolls-tan.md, packages/sdk/src/send/send.js
#1717
- fix type definition for `args` in `send`
=> PKG -- [sdk] Fixed args type for send

.changeset/blue-eggs-care.md
We should patch bump FCL as well so that the new SDK changes can be reflected
=> Bump FCL & add changeset for SDK typedef patch

.changeset/perfect-bananas-deny.md, packages/transport-http/src/http-request.js
cross-fetch doesn't set res.body.  I don't think `res.text()` will actually run into a scenario where it throws (i.e. non utf-8 response), but I catch error just in case
closes #1762
=> PKG -- [transport-http] Fix responseBody not included in errors

packages/fcl-bundle/src/build/get-input-options.js
Closes #1779 
Surprisingly simple fix.  Apparently `rollup-plugin-typescript2` doesn't ingest .js files by default.
=> Fix JSDoc type generation

.changeset/slow-peaches-vanish.md, packages/fcl/src/fcl.js, packages/fcl/src/utils/web/default-config.js, packages/fcl/src/utils/web/index.js, packages/fcl/src/utils/web/storage.js
=> PKG -- [fcl] Default to localStorage

.changeset/healthy-crabs-unite.md, .changeset/slimy-buses-confess.md, packages/fcl/src/exec/utils/derive-dependencies.js, packages/fcl/src/interaction-template-utils/derive-cadence-by-network.js, packages/fcl/src/interaction-template-utils/derive-cadence-by-network.test.js, packages/fcl/src/normalizers/interaction-template/interaction-template.js
closes: https://github.com/onflow/fcl-js/issues/1810
First step to execute v1.1.0 template
=> add support for running cadence from 1.1.0 flix json files

package-lock.json, packages/sdk/src/build/build-authorizations.js, packages/sdk/src/build/build-payer.js, packages/sdk/src/build/build-proposer.js, packages/sdk/src/interaction/interaction.ts, packages/typedefs/src/interaction.ts
follows up on https://github.com/onflow/fcl-js/pull/1802
=> PKG -- [typedefs] Switch interaction-related constants to enums

.changeset/poor-kids-care.md, packages/fcl-core/src/app-utils/verify-signatures.js, packages/fcl-core/src/exec/query.js, packages/fcl-core/src/interaction-template-utils/get-interaction-template-audits.js, packages/fcl-core/src/interaction-template-utils/utils/find-imports.test.js, packages/sdk/src/build/build-script.test.js, packages/sdk/src/resolve/resolve-cadence.test.js, packages/transport-grpc/src/send-execute-script.test.js, packages/transport-http/src/send-execute-script.test.js
closes #1833 
Updates access modifiers to support Cadence 1.0.  There may be some other changes to FCLCrypto depending on how we go about migrating FCLCrypto and satisfying https://github.com/onflow/fcl-contracts/issues/18.  However this is a good pre-emptive change.
=> Update access modifiers to support Cadence 1.0

packages/fcl-wc/package.json
to avoid error
```
SyntaxError: Cannot use import statement outside a module
```
when using `@onflow/fcl-wc` in vite + TS environment
=> fix: @onflow/fcl-wc in vite + TS envirtonment

.changeset/giant-bananas-watch.md, packages/sdk/src/decode/decode.js, packages/sdk/src/decode/decode.test.js, packages/types/README.md, packages/types/src/types.test.ts, packages/types/src/types.ts
=> Update SDK encoding/decoding for Cadence 1.0

.changeset/red-dodos-march.md, packages/fcl-wc/src/service.js
closes #1871 
These were generally unused previously - the only caveat is the WalletConnect "base" service, which did get used by discovery.  However, this service should be the responsibility of FCL Discovery - IF we still want to show it
(I would argue that that any usage of the WalletConnect selection modal at all is just a shortcut, and ultimately it is the responsibility of FCL Discovery to list FCL wallets - as we do with "Flow Wallet" currently)
=> Remove client services from FCL-WC plugin

package-lock.json, package.json, packages/fcl-ethereum-provider/package.json, packages/fcl-ethereum-provider/src/hash-utils.test.ts, packages/fcl-ethereum-provider/src/hash-utils.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-signtypeddata.ts, packages/fcl-ethereum-provider/src/rpc/rpc-processor.ts, packages/fcl-ethereum-provider/src/types/eth.ts
https://github.com/onflow/fcl-js/issues/2057
=> Add `eth_signTypedData`

packages/fcl-ethereum-provider/src/accounts/account-manager.test.ts, packages/fcl-ethereum-provider/src/accounts/account-manager.ts, packages/fcl-ethereum-provider/src/cadence.ts, packages/fcl-ethereum-provider/src/constants.ts, packages/fcl-ethereum-provider/src/create-provider.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-accounts.test.ts, packages/fcl-ethereum-provider/src/rpc/handlers/eth-accounts.ts, packages/fcl-ethereum-provider/src/rpc/rpc-processor.ts
https://github.com/onflow/fcl-js/issues/2112
=> Create COA on request accounts

README.md
Fix broken link to type definitions in README
What does this PR do?
- Updates the incorrect link in `README.md` that pointed to a non-existent `index.ts` file.
- Ensures the correct file reference is provided to avoid confusion for users looking for TypeScript definitions.
Why is this needed?
- The previous link pointed to `./packages/typedefs/src/index.ts`, which does not exist.
- This fixes the documentation so developers can correctly locate type definitions.
Checklist
#2232
=> Fix broken type definition link in README #2232

packages/kit/src/hooks/useFlowQuery.test.ts, packages/kit/src/hooks/useFlowQuery.ts
https://github.com/onflow/fcl-js/issues/2262
```
const { data, isLoading, error, refetch } = useFlowQuery({
enabled: !!user?.addr, // Only enable query when user.addr is truthy
cadence: `
pub fun main(userAddr: Address): Int {
return 42
}
`,
args: (arg, t) => [arg(user!.addr, t.Address)],
});
```
=> Add enabled flag to query hook

packages/kit/src/components/TransactionDialog.tsx, packages/kit/src/icons/CircleCheckIcon.tsx, packages/kit/src/icons/LoaderCircleIcon.tsx
https://github.com/onflow/fcl-js/issues/2495
=> Add `TransactionDialog` component

.changeset/upset-sides-wait.md, packages/react-sdk/src/provider/GlobalTransactionProvider.tsx
=> Clear transaction id so that on error it clears up
